use pymupdf to extract the text in the epubs

In [ ]:
import pymupdf
import os

print(os.listdir("./booksEpub"))

ebookContent = {}

for i in os.listdir("./booksEpub"):
    ebookText = ""
    titlePageText = ""
    filePath = "./booksEpub/" + i
    doc = pymupdf.open(filePath)
    for chapter in range(doc.chapter_count):
        print(f"Chapter {chapter}")
        if chapter==0:
            # get the texts and it will be the key
            currentPage = doc[(0,0)]
            titlePageText = currentPage.get_text()
        else:
            for page in range(doc.chapter_page_count(chapter)):
                print(f"page {page}")
                currentPage = doc[(chapter, page)]
                currentText = currentPage.get_text()
                print(currentText)
                # check if it's the last few pages
                if not(("Brought to you by" in currentText) or ("International License" in currentText) or ("Table of Contents" in currentText) or ("This book was developed as part of the ABC" in currentText) or ("Advancing Basic Education in the Philippines" in currentText)):
                    ebookText+=currentText
                else:
                    pass
    
    #print(ebookText)
    ebookContent[titlePageText] = ebookText

write down the extracted text into .txt files

In [ ]:
import re

for key in ebookContent.keys():
    print(key)
    processedKey = re.sub(r'[\.]','',key)
    processedKey = re.sub(r' ','_',processedKey)
    processedKey = re.sub(r'\?','',processedKey)
    processedKey = re.sub(r'\n','_',processedKey)
    f = open(f"./textData1_pymupdf/{processedKey}.txt","w",encoding='utf-8')
    #print(ebookContent[key])
    f.writelines(ebookContent[key])
    f.close()
    #print("DONE")

consolidate all into one file

In [10]:
import os
import re

sourceFolder = "./textData1_pymupdf"

totalText = ""

# format the text correctly first
for i in os.listdir(sourceFolder):
    filePathForTokenizingText = f"{sourceFolder}/{i}"
    f = open(filePathForTokenizingText,'r', encoding='utf-8')
    insideText = f.read()
    f.close()

    #formatting with regex

    insideText = re.sub(r'[.]','. ',insideText)
    insideText = re.sub('\n',' ',insideText)
    insideText = re.sub('- ','-',insideText)
    insideText = re.sub('  ',' ',insideText)
    insideText = re.sub('&nbsp;','',insideText)

    totalText += insideText
    totalText += "\n\n"

f2 = open("./textData_forTokenization/textAll.txt", "w", encoding='utf-8')
f2.writelines(totalText)
f2.close()

# FSPOST

# Vocabulary

In [1]:
import os

postagged_filepath = "./textData_postagged/textAll_tagged_FINAL.txt"

vocabulary = set()

f = open(f"{postagged_filepath}", "r", encoding="utf-8")
story = f.read()
    
for sentence in story.split('\n'):
    for token in sentence.split(' '):
        vocabulary.add(token)

FileNotFoundError: [Errno 2] No such file or directory: './textData_postagged/textAll_tagged_FINAL.txt'

In [ ]:
import pandas as pd

vocabulary_F = vocabulary.remove('')

vocab_df = pd.DataFrame(list(vocabulary), columns=['tokens'])
vocab_df['lemma'] = vocab_df['tokens'].apply(lambda x: x.split('|')[0])
vocab_df['postag'] = vocab_df['tokens'].apply(lambda x: x.split('|')[1])
vocab_df

In [39]:
pd.set_option('display.max_rows', None)
print(vocab_df.loc[ vocab_df['postag']=="NNC" ]['tokens'].shape)
vocab_df.loc[ vocab_df['postag']=="NNC" ]['tokens']

(618,)

0                kapatid|NNC
2               simangot|NNC
6                pintuan|NNC
11                  baso|NNC
16                  usok|NNC
20               kutsara|NNC
24               krayola|NNC
25               paligid|NNC
29                bulong|NNC
30                 bunga|NNC
34              paghinga|NNC
44                lupain|NNC
45                    Pa|NNC
52                balita|NNC
59               sandali|NNC
62               balyena|NNC
66              senyales|NNC
67                 grado|NNC
71                 tanim|NNC
75                  ulap|NNC
86                kusina|NNC
90              meryenda|NNC
91                 niyog|NNC
99                 plano|NNC
103               kamote|NNC
104                baboy|NNC
115                dahan|NNC
116                basag|NNC
119             kamoteng|NNC
122             kaharian|NNC
135               tanong|NNC
139               aalala|NNC
147               tansan|NNC
153               regalo|NNC
154                 alis|NNC
157                 misa|NNC
164                 akda|NNC
166                 lobo|NNC
167                lipad|NNC
182          papelastika|NNC
191                lugar|NNC
197              talisay|NNC
198                pares|NNC
199                 imik|NNC
200               presyo|NNC
204                 sabi|NNC
211                laing|NNC
215                babae|NNC
217                tawag|NNC
218                 aaya|NNC
226                tribo|NNC
227                saliw|NNC
234               ibabaw|NNC
235               kalaro|NNC
237                ideya|NNC
248            panaginip|NNC
250                 ilaw|NNC
252            restawran|NNC
253                kahon|NNC
255             paibabaw|NNC
259            karagatan|NNC
269                hamon|NNC
270                 sako|NNC
272                ingay|NNC
277              pamilya|NNC
281                gamit|NNC
284                parte|NNC
285              talunan|NNC
290              sibuyas|NNC
294                papel|NNC
301                 iyak|NNC
308               tingin|NNC
312                bayan|NNC
317               usupan|NNC
321              tirahan|NNC
323                 agos|NNC
328          pangingisda|NNC
335             chainsaw|NNC
340                buhos|NNC
342               dibdib|NNC
344               bilang|NNC
346            kalagayan|NNC
349                 alab|NNC
352             sampalok|NNC
357             paborito|NNC
361                lilim|NNC
362                 Kuya|NNC
365               hangin|NNC
366                 kape|NNC
374          eskuwelahan|NNC
386                bigas|NNC
388              bintana|NNC
390                 sala|NNC
391                 luha|NNC
393          kasangkapan|NNC
401                  tao|NNC
407                  mam|NNC
408                hugis|NNC
415               teksto|NNC
416                  asa|NNC
417              sinulid|NNC
421                 laki|NNC
422                dilim|NNC
425             tindahan|NNC
429                 kama|NNC
433                hinay|NNC
441               kidlat|NNC
443               kwento|NNC
446                 Diba|NNC
447           Sumimangot|NNC
453                kagat|NNC
455              pinsala|NNC
459               pagong|NNC
460                 suka|NNC
461          pagbabahagi|NNC
470            kalamansi|NNC
474                likod|NNC
478                uling|NNC
493                 Isda|NNC
497           halakhakan|NNC
498             kuryente|NNC
503             eroplano|NNC
505                butil|NNC
509                dagat|NNC
512                alaga|NNC
514                  opo|NNC
519     pagtatarabahuhan|NNC
522               pigura|NNC
524               pisara|NNC
527             pagbukas|NNC
532               gulong|NNC
542              kalaban|NNC
550               hardin|NNC
559              alukaba|NNC
563              pasilyo|NNC
564             pagputok|NNC
568                sahig|NNC
570                 Mama|NNC
572               pating|NNC
573          kapahamakan|NNC
583              tabagak|NNC
585                 keso|NNC
591              katawan|NNC
593                 haba|NNC
596             kumidlat|NNC
601           pagkakaiba|NNC
614                buhay|NNC
619          pamamagitan|NNC
625            bisikleta|NNC
630                mundo|NNC
631                tanda|NNC
632              paninda|NNC
634                tugon|NNC
641                 maya|NNC
644                talon|NNC
650                grupo|NNC
654                aayos|NNC
655                kahoy|NNC
660              tularan|NNC
664                 toyo|NNC
666         ikinabubuhay|NNC
674                kasya|NNC
675              galamay|NNC
677                 dali|NNC
684                ganda|NNC
688           pagmamahal|NNC
701                elesi|NNC
706              klasrum|NNC
710              lungsod|NNC
712                 lupa|NNC
726        kapangyarihan|NNC
727                  Dun|NNC
728              butones|NNC
736           panghuhuli|NNC
740              pagkain|NNC
746                 kwak|NNC
748                tigil|NNC
752           papelastik|NNC
755                 sari|NNC
756                kaisa|NNC
760                 alon|NNC
762                 gabi|NNC
768               gawain|NNC
769            mamingwit|NNC
770            pahiwatig|NNC
773                patak|NNC
775                 ahas|NNC
777           kabundukan|NNC
788              liwanag|NNC
792            paglangoy|NNC
796           pagdrowing|NNC
799                 susi|NNC
803                 puso|NNC
816                 taas|NNC
817             Sumagang|NNC
822              katribo|NNC
831             pagtawag|NNC
832                 sapa|NNC
836             panangga|NNC
837          nakatatanda|NNC
847                 damo|NNC
859                kanin|NNC
866            managinip|NNC
867              balikat|NNC
870               itsura|NNC
878             paaralan|NNC
883                 kaba|NNC
885                   Aw|NNC
896              pagsang|NNC
902                Sayaw|NNC
907             kaingero|NNC
908                hapon|NNC
909                batik|NNC
912            pamumuhay|NNC
916                kurap|NNC
918                beses|NNC
928                bagay|NNC
929          mangingisda|NNC
930                 taon|NNC
933               bituin|NNC
938             pangalan|NNC
941               pugita|NNC
943                tunog|NNC
946               paalam|NNC
949               siyato|NNC
952            karanasan|NNC
957                itlog|NNC
961            paglampas|NNC
963          Dumadausdos|NNC
968             alimasag|NNC
970                 kita|NNC
982              insekto|NNC
988              papasok|NNC
1002                baha|NNC
1010                kuha|NNC
1011                nigo|NNC
1013              binata|NNC
1015             tahanan|NNC
1021            alikabok|NNC
1023             kalsada|NNC
1025                mama|NNC
1029              korona|NNC
1041                 Mam|NNC
1045           kabahayan|NNC
1051                 ΓÇÖ|NNC
1052              hiling|NNC
1059             inuming|NNC
1070           paliwanag|NNC
1071              taguan|NNC
1072              gulang|NNC
1075          bulawbulaw|NNC
1078                bato|NNC
1082             sapatos|NNC
1083                Ewan|NNC
1084            sisidlan|NNC
1089                bote|NNC
1092             Larawan|NNC
1103                lolo|NNC
1107                utos|NNC
1108       pagkakaibigan|NNC
1116              ngipin|NNC
1124              titser|NNC
1125               tubig|NNC
1128               anino|NNC
1138                Lolo|NNC
1145              paraan|NNC
1150           puluputan|NNC
1151             pasukan|NNC
1157                loob|NNC
1162               buwan|NNC
1173                pusa|NNC
1176            biskuwit|NNC
1182                ikot|NNC
1184             damuhan|NNC
1188             hapunan|NNC
1191             palitan|NNC
1198            pangisda|NNC
1201          pangyayari|NNC
1202               palay|NNC
1209               sagot|NNC
1211               klase|NNC
1214          pagkasakim|NNC
1218               duyan|NNC
1220                ulan|NNC
1233                 ari|NNC
1238             bathala|NNC
1245               Sigaw|NNC
1249             pagtaas|NNC
1250            panganay|NNC
1255                Lani|NNC
1258                dami|NNC
1261                puno|NNC
1268           halimbawa|NNC
1271                tuwa|NNC
1272             hamapas|NNC
1273             sumbong|NNC
1275            atensyon|NNC
1284               alala|NNC
1292               sanga|NNC
1294              pataas|NNC
1298              tumpok|NNC
1299               bukal|NNC
1313            bulaklak|NNC
1317                taya|NNC
1324                 Mag|NNC
1325                unan|NNC
1328              bangka|NNC
1331                 Ins|NNC
1339           mananayaw|NNC
1341         pamimingwit|NNC
1344          pakiramdam|NNC
1352            paggamit|NNC
1354               Itlog|NNC
1363              langoy|NNC
1364             bakuran|NNC
1367                  yo|NNC
1378               bilog|NNC
1383              kislap|NNC
1392              eksena|NNC
1397               bunot|NNC
1398              anakan|NNC
1404            pakialam|NNC
1414                pala|NNC
1416           direksyon|NNC
1423           kasiyahan|NNC
1425             tawanan|NNC
1429             iskuter|NNC
1430                alay|NNC
1435            kalayuan|NNC
1439         imprentahan|NNC
1440               nanay|NNC
1442               ngiti|NNC
1443               sisiw|NNC
1445               bilis|NNC
1449                 aso|NNC
1454                Kwak|NNC
1457               porma|NNC
1462             retrato|NNC
1463               habol|NNC
1471                asim|NNC
1475              kuwago|NNC
1477             hugasan|NNC
1479                 ulo|NNC
1483        dalampasigan|NNC
1485               rhino|NNC
1486               turan|NNC
1500                Luna|NNC
1502              tutubi|NNC
1509               libro|NNC
1510          kalangitan|NNC
1515          magkakampi|NNC
1518              saging|NNC
1524          karamdaman|NNC
1526              hihihi|NNC
1528            katwiran|NNC
1530            kaarawan|NNC
1534               dahon|NNC
1548          pagsasalin|NNC
1554             palayan|NNC
1562                ibon|NNC
1564            pagtagpi|NNC
1567                  aw|NNC
1568           mamumutol|NNC
1572             habagat|NNC
1577             didilig|NNC
1587              bundok|NNC
1591           kaganapan|NNC
1597                poso|NNC
1599                dyan|NNC
1601              kausap|NNC
1606                sama|NNC
1607             kumulog|NNC
1621               palad|NNC
1625               imbak|NNC
1638            dingding|NNC
1640              kwarto|NNC
1646                  Uy|NNC
1649                 bag|NNC
1653               pasok|NNC
1660               uulan|NNC
1663            Pasensya|NNC
1680               uusap|NNC
1687                oras|NNC
1691                tupi|NNC
1692                dulo|NNC
1694                Luha|NNC
1696                tora|NNC
1716                gawi|NNC
1720             kabinet|NNC
1724                kesa|NNC
1728            nilalang|NNC
1732               ugali|NNC
1742              bahagi|NNC
1749                 ina|NNC
1753              tulong|NNC
1755                araw|NNC
1758              manilo|NNC
1759             taniman|NNC
1763           ikabubuti|NNC
1765              ilahas|NNC
1767               tatay|NNC
1770                isip|NNC
1779             trabaho|NNC
1780            baluktot|NNC
1782            buhangin|NNC
1784            elepante|NNC
1785                kuya|NNC
1786             pabango|NNC
1789           talahiban|NNC
1792              unggoy|NNC
1794               hinga|NNC
1800             palabas|NNC
1801           balkonahe|NNC
1805                yaya|NNC
1806               kulog|NNC
1815              buntot|NNC
1819               balat|NNC
1821                Bato|NNC
1823            magulang|NNC
1824               sitaw|NNC
1830                Lisa|NNC
1832          lalanguyan|NNC
1833              bangin|NNC
1834              daanan|NNC
1835             korales|NNC
1844               aklat|NNC
1849           pakatapos|NNC
1851              karton|NNC
1852              aralan|NNC
1856             bituwin|NNC
1858              sapsap|NNC
1862            problema|NNC
1863                 Yan|NNC
1866         publication|NNC
1868               pagod|NNC
1869                 nun|NNC
1870              kuweba|NNC
1876        kapitbahayan|NNC
1885             kaklase|NNC
1886                ilog|NNC
1890             lambing|NNC
1894             langgam|NNC
1903             pasayan|NNC
1906             tinapay|NNC
1910               ilong|NNC
1914                daga|NNC
1917               kulay|NNC
1919               sigaw|NNC
1925               silid|NNC
1933               hayop|NNC
1963               hawak|NNC
1964          paglalakad|NNC
1967                 Ate|NNC
1968             larawan|NNC
1969                 ΓÇÿ|NNC
1980              kuneho|NNC
1981              tuktok|NNC
1998        pagtatrabaho|NNC
1999                wika|NNC
2002               takot|NNC
2014            Bulaklak|NNC
2015             lampara|NNC
2034                ulam|NNC
2039             halaman|NNC
2040             salawal|NNC
2051             paglaki|NNC
2053             pinggan|NNC
2057           pagbagsak|NNC
2066              bitbit|NNC
2073           pagsasama|NNC
2074           kasagutan|NNC
2076              kabibe|NNC
2078               silip|NNC
2079             panahon|NNC
2081                saya|NNC
2092             managat|NNC
2100              dahoon|NNC
2102                aral|NNC
2110            bulungan|NNC
2115               labas|NNC
2120             habulan|NNC
2122               bunso|NNC
2126               galaw|NNC
2127          paghakbang|NNC
2130            pasamano|NNC
2131            Gumuguho|NNC
2147               abala|NNC
2149               laman|NNC
2152          ilustrador|NNC
2153              laruan|NNC
2154          karpintero|NNC
2163                apoy|NNC
2168                labi|NNC
2170              palaka|NNC
2178              tabing|NNC
2180               rolyo|NNC
2184              sagana|NNC
2194             kamusta|NNC
2197                 Nay|NNC
2199               lakas|NNC
2202              agimat|NNC
2208                bata|NNC
2212                ihip|NNC
2213               yakap|NNC
2224            sitsirya|NNC
2227               tigre|NNC
2235               upuan|NNC
2242               harap|NNC
2245           panloloko|NNC
2250               pugad|NNC
2253             pananim|NNC
2254            karakter|NNC
2261                 ani|NNC
2262            simbahan|NNC
2263                  Ma|NNC
2265              batuan|NNC
2269               barko|NNC
2277               sabon|NNC
2282           matatanda|NNC
2284                init|NNC
2291               kanta|NNC
2294               bukid|NNC
2302                tsok|NNC
2303         magkaibigan|NNC
2309           katandaan|NNC
2321           pagkauhaw|NNC
2323               Gabay|NNC
2329               hukay|NNC
2332               oyayi|NNC
2337               ingat|NNC
2356               mukha|NNC
2358               patay|NNC
2363            pagbalik|NNC
2366               laban|NNC
2367                Ping|NNC
2368               donut|NNC
2370              singko|NNC
2372                Iyan|NNC
2376            pagputol|NNC
2378               pinto|NNC
2380               balik|NNC
2381               bitag|NNC
2385               malay|NNC
2391         paghihintay|NNC
2398              anyaya|NNC
2411               Tatay|NNC
2412             uumpisa|NNC
2413                alok|NNC
2418           Kamayanan|NNC
2421              lalaki|NNC
2423              pinsan|NNC
2424                 Opo|NNC
2425               hamog|NNC
2426               plato|NNC
2433            Pagpasok|NNC
2443          eskwelahan|NNC
2448           pagtulong|NNC
2460               bulsa|NNC
2471                pato|NNC
2478             salamin|NNC
2481                 upo|NNC
2482                daan|NNC
2489            kaibigan|NNC
2492             kuwarto|NNC
2494                papa|NNC
2501                tuka|NNC
2506               Nanay|NNC
2507          magkapatid|NNC
2515                huni|NNC
2516             garapon|NNC
2519              sarili|NNC
2526               sakit|NNC
2529               bahay|NNC
2531               galit|NNC
2539                 ama|NNC
2553            kakambal|NNC
2563        pagmamakaawa|NNC
2568           kalamidad|NNC
2570             tagpiin|NNC
2575              kabayo|NNC
2580                taka|NNC
2586            pakiusap|NNC
2588              langit|NNC
2591                lawa|NNC
2593                Lola|NNC
2595                anak|NNC
2602                talo|NNC
2605             siyudad|NNC
2627                miss|NNC
2628             pahayag|NNC
2645            pagulong|NNC
2648             pampang|NNC
2650              hantik|NNC
2651                asan|NNC
2654             tilapya|NNC
2656               pauwi|NNC
2667              Tulong|NNC
2672                lola|NNC
2681               kamay|NNC
2685                baka|NNC
2694               Titay|NNC
2696                isda|NNC
2699           kagubatan|NNC
2703               aaral|NNC
2711             okasyon|NNC
2714               gulay|NNC
2715               liksi|NNC
2723                 ΓÇ¥|NNC
2731               Hello|NNC
2732                mata|NNC
2736          alalahanin|NNC
2743             Balabaw|NNC
2751               butas|NNC
2752                 uod|NNC
2759               damit|NNC
2769              paslit|NNC
2770               boses|NNC
2775               batis|NNC
Name: tokens, dtype: object

In [43]:
# get the vocabulary and the sentences into the Organized_Text_data folder in the form of csv's

import pandas as pd

#vocab_df.to_csv("./Organized_Text_data/vocabulary.csv")

sentenceInp = open("./textData_postagged/textAll_tagged_final.txt", 'r', encoding='utf-8')
sentenceDF = pd.DataFrame(sentenceInp.readlines(), columns=['sentence'])
sentenceDF.to_csv("./Organized_Text_data/sentences.csv")

### The machine learning part after preprocessing

@inproceedings{kuran2024hybrid,
  title={A HYBRID BILSTM-CRF MODEL WITH BERT EMBEDDINGS FOR NAMED ENTITY RECOGNITION ON CONFIDENTIAL SYNTHETIC DATA},
  author={Kuran, Emre Can and Elen, Abdullah and Kuran, Umut},
  booktitle={V. INTERNATIONAL SCIENCE AND INNOVATION CONGRESS (INSI 2024) PROCEEDINGS BOOK},
  pages={16}
}

FIlipino corpus
(source: https://huggingface.co/datasets/linkanjarad/Wikitext-TL39/tree/main)

ELMO DOESN"T WORK

In [2]:
# convert parquet to text
import pandas as pd
import fastparquet
import pyarrow
import numpy as np

wikiData = pd.read_parquet('./Pre-training/train.parquet')
wikiData.to_csv('./Pre-training/train.txt', header=None, index=None, sep='\n', mode='a')

In [11]:
# clean up the pre-training data
import re

readTrain = open('./Pre-training/train.txt', 'r', encoding='utf-8')
writeThis = re.sub(r"= [a-zA-Z ]+ =", '',readTrain.read())
writeTrain = open('./Pre-training/train_1.txt', 'w', encoding='utf-8')
writeTrain.write(writeThis)

208798244

In [18]:
import re
import pandas as pd

readTrain = open('./Pre-training/train.txt', 'r', encoding='utf-8')
allTopics = re.findall(r"= [a-zA-Z ]+ =", readTrain.read())
allTopicsFinal = []
for i in allTopics:
    allTopicsFinal.append(i[2:-2])

pd.DataFrame(allTopicsFinal, columns=['topics']).to_csv("./Organized_Text_data/vocabulary_wiki_tl39.csv")

In [ ]:
# compare vocabularies
import pandas as pd

filwordnet_lemmas = pd.read_csv("./Organized_Text_data/filWordNetLemmas.csv")['lemma'].to_frame()
preTrain_topics = pd.read_csv("./Organized_Text_data/vocabulary_wiki_tl39.csv")['topics'].to_frame()
childrensBook_vocabulary = pd.read_csv("./Organized_Text_data/vocabulary.csv")['lemma'].to_frame()

filwordnet_lemmas.columns = ['vocabulary']
preTrain_topics.columns = ['vocabulary']
childrensBook_vocabulary.columns = ['vocabulary']

filwordnet_lemmas['vocabulary'] = filwordnet_lemmas['vocabulary'].str.lower()
preTrain_topics['vocabulary'] = preTrain_topics['vocabulary'].str.lower()
childrensBook_vocabulary['vocabulary'] = childrensBook_vocabulary['vocabulary'].str.lower()

#print(f"{filwordnet_lemmas.info()} {preTrain_vocabulary.info()} {childrensBook_vocabulary.info()}")

filwordnet_preTrain = filwordnet_lemmas.merge(preTrain_topics, how='inner', on=['vocabulary']).drop_duplicates()
filwordnet_childrensBook = filwordnet_lemmas.merge(childrensBook_vocabulary, how='inner', on=['vocabulary']).drop_duplicates()
preTrain_childrensBook = preTrain_topics.merge(childrensBook_vocabulary, how='inner', on=['vocabulary']).drop_duplicates()

allmerge = filwordnet_preTrain.merge(preTrain_childrensBook, how='inner', on=['vocabulary']).drop_duplicates()

print(f'''
Length of the intersection of each dataset=======================
filwordnet_preTrain: {filwordnet_preTrain.shape[0]}
filwordnet_childrensBook: {filwordnet_childrensBook.shape[0]}
preTrain_childrensBook: {preTrain_childrensBook.shape[0]}
AllDatasets: {allmerge.shape[0]}

''')

Length of the intersection of each dataset=======================
filwordnet_preTrain: 1651
filwordnet_childrensBook: 364
preTrain_childrensBook: 292
AllDatasets: 149

In [24]:
# topic finder sa wiki
import pandas as pd
import re
import json

topicList = pd.concat((filwordnet_preTrain, preTrain_childrensBook)).drop_duplicates()['vocabulary'].str.lower().tolist()
topicSet = set(topicList)

readTrain = open('./Pre-training/train.txt', 'r', encoding='utf-8')
readTrainText = readTrain.readlines()
readTrainText

topicDict_withExamples = {}
currentTopic = "DELETE_THIS_KEY"

for line in readTrainText:
    #print(line, currentTopic)
    if(line[0] == '='):
        # check if the thing we're looking at is at this list
        toCheck = line[2:-3]
        if toCheck.lower() in topicSet:
            currentTopic = toCheck
            #print(currentTopic)
            topicDict_withExamples[currentTopic] = []
        else:
            currentTopic = "DELETE_THIS_KEY"
    else:
        if currentTopic != "DELETE_THIS_KEY":
            topicDict_withExamples[currentTopic].append(line)
        else:
            pass

with open("./Organized_Text_data/topic_withExamples.json", "w") as outfile: 
    json.dump(topicDict_withExamples, outfile)

In [15]:
# merge all sentences in the common topic thing into a single text file
import json
import math as m

commonTopics = open("./Organized_Text_data/topic_withExamples.json")
data = json.load(commonTopics)

keyChunks = []
chunk_count = 4
keylist = list(data.keys())

chunk_size = m.ceil(len(keylist)/chunk_count)

for i in range(chunk_count):
    keyChunks.append(keylist[(chunk_size*i): (chunk_size*(i+1))])

chunk_ind = 1
for chunk in keyChunks:
    sentenceList = []

    for key in chunk:
        for sentence in data[key]:
            sentenceList.append(sentence)

    sentenceList_file = open(f"./Pre-training/train_common_lite_{chunk_ind}.txt", "w", encoding='utf-8')
    sentenceList_file.writelines(sentenceList)
    sentenceList_file.close()
    chunk_ind+=1

# Letsreadasia vocabulary
The queries to answer the research questions are also here

In [2]:
# generate the letsreadasia vocabulary
import pandas as pd

f = open('./postagging/textAllFil_postagged_FINAL.txt', 'r')
entire_thing = f.read()
f.close()

token_set = set()

for token in entire_thing.strip().split():
    if '|' in token:
        token_set.add(token)

token_df = pd.DataFrame(list(token_set), columns=['tokens'])
token_df['lemma'] = token_df['tokens'].apply(lambda x:x.split('|')[0])
token_df['postag'] = token_df['tokens'].apply(lambda x:x.split('|')[1])

token_df.to_csv("Organized_Text_data/vocabulary_letsreadasia.csv")
token_df

                  tokens          lemma postag
0          sinasali|VBTR       sinasali   VBTR
1               Foxy|NNP           Foxy    NNP
2             School|NNP         School    NNP
3      panghihikayat|JJD  panghihikayat    JJD
4          paguugali|NNC      paguugali    NNC
...                  ...            ...    ...
17315     masagasaan|VBW     masagasaan    VBW
17316       Itinaas|VBOF        Itinaas   VBOF
17317           laso|NNC           laso    NNC
17318      namasyal|VBTS       namasyal   VBTS
17319     nalalanta|VBTR      nalalanta   VBTR

[17320 rows x 3 columns]

In [7]:
token_df.loc[token_df['lemma'].str.contains(r'[.|?|!]') & token_df['postag'].str.contains('NNC')].drop_duplicates().values.tolist()

[['orasan.orasan|NNC', 'orasan.orasan', 'NNC'],
 ['g.|NNCA', 'g.', 'NNCA'],
 ['eroplano.|NNC', 'eroplano.', 'NNC'],
 ['kambing.nagsimula|NNC', 'kambing.nagsimula', 'NNC'],
 ['......|NNC', '......', 'NNC'],
 ['single.letsreadasia.org|NNC', 'single.letsreadasia.org', 'NNC'],
 ['www.idriesshahfoundation.org|NNC', 'www.idriesshahfoundation.org', 'NNC'],
 ['paglalaro.at|NNC', 'paglalaro.at', 'NNC'],
 ['mo.|NNCA', 'mo.', 'NNCA'],
 ['etc.|NNCA', 'etc.', 'NNCA'],
 ['http://litara.or.id/|NNC', 'http://litara.or.id/', 'NNC'],
 ['kanya.malungkot|NNC', 'kanya.malungkot', 'NNC'],
 ['sungay.dahan|NNC', 'sungay.dahan', 'NNC'],
 ['panulat.klik|NNC', 'panulat.klik', 'NNC'],
 ['ako......basang|NNC_CCP', 'ako......basang', 'NNC_CCP'],
 ['kanya.pagkaraan|NNC', 'kanya.pagkaraan', 'NNC'],
 ['bahay.at|NNC', 'bahay.at', 'NNC']]

In [12]:
print(len(token_df.loc[token_df['postag']=='NNC'].values.tolist()))
token_df.loc[token_df['postag']=='NNC'].values.tolist()

3328

[['kondisyon|NNC', 'kondisyon', 'NNC'],
 ['Gng|NNC', 'Gng', 'NNC'],
 ['ugat|NNC', 'ugat', 'NNC'],
 ['hardin|NNC', 'hardin', 'NNC'],
 ['pagsimangot|NNC', 'pagsimangot', 'NNC'],
 ['bundok|NNC', 'bundok', 'NNC'],
 ['Katangian|NNC', 'Katangian', 'NNC'],
 ['kartoon|NNC', 'kartoon', 'NNC'],
 ['tariktik|NNC', 'tariktik', 'NNC'],
 ['pagdaan|NNC', 'pagdaan', 'NNC'],
 ['Uwak|NNC', 'Uwak', 'NNC'],
 ['kuwago|NNC', 'kuwago', 'NNC'],
 ['restawran|NNC', 'restawran', 'NNC'],
 ['pagbabahaginan|NNC', 'pagbabahaginan', 'NNC'],
 ['Paa|NNC', 'Paa', 'NNC'],
 ['tabang|NNC', 'tabang', 'NNC'],
 ['ate|NNC', 'ate', 'NNC'],
 ['klinika|NNC', 'klinika', 'NNC'],
 ['Mambabasa|NNC', 'Mambabasa', 'NNC'],
 ['asikaso|NNC', 'asikaso', 'NNC'],
 ['panaderya|NNC', 'panaderya', 'NNC'],
 ['pasahero|NNC', 'pasahero', 'NNC'],
 ['gasera|NNC', 'gasera', 'NNC'],
 ['pukyutan|NNC', 'pukyutan', 'NNC'],
 ['pagbaba|NNC', 'pagbaba', 'NNC'],
 ['bato|NNC', 'bato', 'NNC'],
 ['salaysay|NNC', 'salaysay', 'NNC'],
 ['tsaleko|NNC', 'tsaleko', 'NNC'],
 ['kapana|NNC', 'kapana', 'NNC'],
 ['동화를많이들려주셨습니다|NNC', '동화를많이들려주셨습니다', 'NNC'],
 ['rayon|NNC', 'rayon', 'NNC'],
 ['papag|NNC', 'papag', 'NNC'],
 ['plasa|NNC', 'plasa', 'NNC'],
 ['patimpalak|NNC', 'patimpalak', 'NNC'],
 ['Pera|NNC', 'Pera', 'NNC'],
 ['baboy|NNC', 'baboy', 'NNC'],
 ['Tatsulok|NNC', 'Tatsulok', 'NNC'],
 ['kutsara|NNC', 'kutsara', 'NNC'],
 ['makata|NNC', 'makata', 'NNC'],
 ['sambayanan|NNC', 'sambayanan', 'NNC'],
 ['pantaboy|NNC', 'pantaboy', 'NNC'],
 ['sarangggola|NNC', 'sarangggola', 'NNC'],
 ['aagawan|NNC', 'aagawan', 'NNC'],
 ['kalagayan|NNC', 'kalagayan', 'NNC'],
 ['ngiti|NNC', 'ngiti', 'NNC'],
 ['lámang|NNC', 'lámang', 'NNC'],
 ['basurahan|NNC', 'basurahan', 'NNC'],
 ['buntot|NNC', 'buntot', 'NNC'],
 ['liham|NNC', 'liham', 'NNC'],
 ['kambing.nagsimula|NNC', 'kambing.nagsimula', 'NNC'],
 ['purple|NNC', 'purple', 'NNC'],
 ['puwet|NNC', 'puwet', 'NNC'],
 ['Iluko|NNC', 'Iluko', 'NNC'],
 ['artikulo|NNC', 'artikulo', 'NNC'],
 ['lunas|NNC', 'lunas', 'NNC'],
 ['tuba|NNC', 'tuba', 'NNC'],
 ['Paratang|NNC', 'Paratang', 'NNC'],
 ['ilog|NNC', 'ilog', 'NNC'],
 ['ugnayan|NNC', 'ugnayan', 'NNC'],
 ['ulit|NNC', 'ulit', 'NNC'],
 ['tagadesinyo|NNC', 'tagadesinyo', 'NNC'],
 ['palapag|NNC', 'palapag', 'NNC'],
 ['kaldero|NNC', 'kaldero', 'NNC'],
 ['pagdatingsa|NNC', 'pagdatingsa', 'NNC'],
 ['pisara|NNC', 'pisara', 'NNC'],
 ['bahagi|NNC', 'bahagi', 'NNC'],
 ['butiki|NNC', 'butiki', 'NNC'],
 ['kagandahan|NNC', 'kagandahan', 'NNC'],
 ['gulaman|NNC', 'gulaman', 'NNC'],
 ['gilid|NNC', 'gilid', 'NNC'],
 ['paslit|NNC', 'paslit', 'NNC'],
 ['alingawngaw|NNC', 'alingawngaw', 'NNC'],
 ['pagtagpi|NNC', 'pagtagpi', 'NNC'],
 ['palaruan|NNC', 'palaruan', 'NNC'],
 ['paalaala|NNC', 'paalaala', 'NNC'],
 ['bituwin|NNC', 'bituwin', 'NNC'],
 ['Atribusyon|NNC', 'Atribusyon', 'NNC'],
 ['unan|NNC', 'unan', 'NNC'],
 ['senyas|NNC', 'senyas', 'NNC'],
 ['tangke|NNC', 'tangke', 'NNC'],
 ['dalang|NNC', 'dalang', 'NNC'],
 ['kuwaderno|NNC', 'kuwaderno', 'NNC'],
 ['pesos|NNC', 'pesos', 'NNC'],
 ['pangungusap|NNC', 'pangungusap', 'NNC'],
 ['pagmamakaawa|NNC', 'pagmamakaawa', 'NNC'],
 ['piniprito|NNC', 'piniprito', 'NNC'],
 ['pansit|NNC', 'pansit', 'NNC'],
 ['pasayan|NNC', 'pasayan', 'NNC'],
 ['dekorasyon|NNC', 'dekorasyon', 'NNC'],
 ['sigawan|NNC', 'sigawan', 'NNC'],
 ['Sentro|NNC', 'Sentro', 'NNC'],
 ['datiles|NNC', 'datiles', 'NNC'],
 ['magkapatid|NNC', 'magkapatid', 'NNC'],
 ['engineering|NNC', 'engineering', 'NNC'],
 ['konstelasyon|NNC', 'konstelasyon', 'NNC'],
 ['kasinliit|NNC', 'kasinliit', 'NNC'],
 ['ayos|NNC', 'ayos', 'NNC'],
 ['eksamen|NNC', 'eksamen', 'NNC'],
 ['yabag|NNC', 'yabag', 'NNC'],
 ['kontrol|NNC', 'kontrol', 'NNC'],
 ['labi|NNC', 'labi', 'NNC'],
 ['kabog|NNC', 'kabog', 'NNC'],
 ['looban|NNC', 'looban', 'NNC'],
 ['tira|NNC', 'tira', 'NNC'],
 ['kasalanan|NNC', 'kasalanan', 'NNC'],
 ['imigrante|NNC', 'imigrante', 'NNC'],
 ['siyato|NNC', 'siyato', 'NNC'],
 ['pusa|NNC', 'pusa', 'NNC'],
 ['pagbibilang|NNC', 'pagbibilang', 'NNC'],
 ['kan|NNC', 'kan', 'NNC'],
 ['puddle|NNC', 'puddle', 'NNC'],
 ['pagkilala|NNC', 'pagkilala', 'NNC'],
 ['leeg|NNC', 'leeg', 'NNC'],
 ['kamay|NNC', 'kamay', 'NNC'],
 ['paika|NNC', 'paika', 'NNC'],
 ['dioksido|NNC', 'dioksido', 'NNC'],
 ['pamayanan|NNC', 'pamayanan', 'NNC'],
 ['pagkakabukas|NNC', 'pagkakabukas', 'NNC'],
 ['paumanhin|NNC', 'paumanhin', 'NNC'],
 ['negosyante|NNC', 'negosyante', 'NNC'],
 ['daklot|NNC', 'daklot', 'NNC'],
 ['anestisya|NNC', 'anestisya', 'NNC'],
 ['papaya|NNC', 'papaya', 'NNC'],
 ['badminton|NNC', 'badminton', 'NNC'],
 ['panakot|NNC', 'panakot', 'NNC'],
 ['ehersisyo|NNC', 'ehersisyo', 'NNC'],
 ['inggit|NNC', 'inggit', 'NNC'],
 ['Pasensya|NNC', 'Pasensya', 'NNC'],
 ['Thang|NNC', 'Thang', 'NNC'],
 ['palaman|NNC', 'palaman', 'NNC'],
 ['sapà|NNC', 'sapà', 'NNC'],
 ['tagapag|NNC', 'tagapag', 'NNC'],
 ['nag|NNC', 'nag', 'NNC'],
 ['palagid|NNC', 'palagid', 'NNC'],
 ['batà|NNC', 'batà', 'NNC'],
 ['pagod|NNC', 'pagod', 'NNC'],
 ['selebrasyon|NNC', 'selebrasyon', 'NNC'],
 ['balita|NNC', 'balita', 'NNC'],
 ['pungas|NNC', 'pungas', 'NNC'],
 ['paninda|NNC', 'paninda', 'NNC'],
 ['paghinga|NNC', 'paghinga', 'NNC'],
 ['pagtataniman|NNC', 'pagtataniman', 'NNC'],
 ['pagmamayabang|NNC', 'pagmamayabang', 'NNC'],
 ['buhangin|NNC', 'buhangin', 'NNC'],
 ['sipilyo|NNC', 'sipilyo', 'NNC'],
 ['Kahanga|NNC', 'Kahanga', 'NNC'],
 ['eroplano.|NNC', 'eroplano.', 'NNC'],
 ['lapad|NNC', 'lapad', 'NNC'],
 ['hihihi|NNC', 'hihihi', 'NNC'],
 ['baga|NNC', 'baga', 'NNC'],
 ['angkop|NNC', 'angkop', 'NNC'],
 ['aaya|NNC', 'aaya', 'NNC'],
 ['bulungan|NNC', 'bulungan', 'NNC'],
 ['anggasera|NNC', 'anggasera', 'NNC'],
 ['paghagis|NNC', 'paghagis', 'NNC'],
 ['Langgam|NNC', 'Langgam', 'NNC'],
 ['bangketa|NNC', 'bangketa', 'NNC'],
 ['grupo|NNC', 'grupo', 'NNC'],
 ['klasrum|NNC', 'klasrum', 'NNC'],
 ['tiyakad|NNC', 'tiyakad', 'NNC'],
 ['kawad|NNC', 'kawad', 'NNC'],
 ['member|NNC', 'member', 'NNC'],
 ['pagbili|NNC', 'pagbili', 'NNC'],
 ['Bibe|NNC', 'Bibe', 'NNC'],
 ['alampay|NNC', 'alampay', 'NNC'],
 ['pagbuo|NNC', 'pagbuo', 'NNC'],
 ['pamilya|NNC', 'pamilya', 'NNC'],
 ['paglalarawan|NNC', 'paglalarawan', 'NNC'],
 ['mais|NNC', 'mais', 'NNC'],
 ['paragliding|NNC', 'paragliding', 'NNC'],
 ['pagnguya|NNC', 'pagnguya', 'NNC'],
 ['palayan|NNC', 'palayan', 'NNC'],
 ['lansangan|NNC', 'lansangan', 'NNC'],
 ['pagtugtog|NNC', 'pagtugtog', 'NNC'],
 ['paglikas|NNC', 'paglikas', 'NNC'],
 ['puwang|NNC', 'puwang', 'NNC'],
 ['yelo|NNC', 'yelo', 'NNC'],
 ['takót|NNC', 'takót', 'NNC'],
 ['tutok|NNC', 'tutok', 'NNC'],
 ['klik|NNC', 'klik', 'NNC'],
 ['tiyo|NNC', 'tiyo', 'NNC'],
 ['giraffe|NNC', 'giraffe', 'NNC'],
 ['orkidas|NNC', 'orkidas', 'NNC'],
 ['mirasol|NNC', 'mirasol', 'NNC'],
 ['hinlalaki|NNC', 'hinlalaki', 'NNC'],
 ['piloto|NNC', 'piloto', 'NNC'],
 ['pamamahala|NNC', 'pamamahala', 'NNC'],
 ['Lola|NNC', 'Lola', 'NNC'],
 ['orasan|NNC', 'orasan', 'NNC'],
 ['babasahin|NNC', 'babasahin', 'NNC'],
 ['papa|NNC', 'papa', 'NNC'],
 ['mantikilya|NNC', 'mantikilya', 'NNC'],
 ['motor|NNC', 'motor', 'NNC'],
 ['animasyon|NNC', 'animasyon', 'NNC'],
 ['pagpatuloy|NNC', 'pagpatuloy', 'NNC'],
 ['sumisipol|NNC', 'sumisipol', 'NNC'],
 ['kakok|NNC', 'kakok', 'NNC'],
 ['kaibuturan|NNC', 'kaibuturan', 'NNC'],
 ['repleksiyon|NNC', 'repleksiyon', 'NNC'],
 ['away|NNC', 'away', 'NNC'],
 ['ayparasito|NNC', 'ayparasito', 'NNC'],
 ['timpalak|NNC', 'timpalak', 'NNC'],
 ['kapahamakan|NNC', 'kapahamakan', 'NNC'],
 ['gusot|NNC', 'gusot', 'NNC'],
 ['sentimetro|NNC', 'sentimetro', 'NNC'],
 ['nobya|NNC', 'nobya', 'NNC'],
 ['dilaan|NNC', 'dilaan', 'NNC'],
 ['bruha|NNC', 'bruha', 'NNC'],
 ['Kasya|NNC', 'Kasya', 'NNC'],
 ['plano|NNC', 'plano', 'NNC'],
 ['gana|NNC', 'gana', 'NNC'],
 ['mikropono|NNC', 'mikropono', 'NNC'],
 ['atensyon|NNC', 'atensyon', 'NNC'],
 ['pamatnugan|NNC', 'pamatnugan', 'NNC'],
 ['pagganap|NNC', 'pagganap', 'NNC'],
 ['kuliflor|NNC', 'kuliflor', 'NNC'],
 ['sikla|NNC', 'sikla', 'NNC'],
 ['pako|NNC', 'pako', 'NNC'],
 ['mananayaw|NNC', 'mananayaw', 'NNC'],
 ['kuwatro|NNC', 'kuwatro', 'NNC'],
 ['pagkasunog|NNC', 'pagkasunog', 'NNC'],
 ['lahatay|NNC', 'lahatay', 'NNC'],
 ['taumbayan|NNC', 'taumbayan', 'NNC'],
 ['katumbas|NNC', 'katumbas', 'NNC'],
 ['tumango|NNC', 'tumango', 'NNC'],
 ['aani|NNC', 'aani', 'NNC'],
 ['kapatawaran|NNC', 'kapatawaran', 'NNC'],
 ['hayoy|NNC', 'hayoy', 'NNC'],
 ['bagyo|NNC', 'bagyo', 'NNC'],
 ['tuko|NNC', 'tuko', 'NNC'],
 ['pagkainpara|NNC', 'pagkainpara', 'NNC'],
 ['laso|NNC', 'laso', 'NNC'],
 ['kumot|NNC', 'kumot', 'NNC'],
 ['palamuti|NNC', 'palamuti', 'NNC'],
 ['저의부모님께이책을선물로드리고싶습니다|NNC', '저의부모님께이책을선물로드리고싶습니다', 'NNC'],
 ['ateDumating|NNC', 'ateDumating', 'NNC'],
 ['patalon|NNC', 'patalon', 'NNC'],
 ['lapis|NNC', 'lapis', 'NNC'],
 ['rambutan|NNC', 'rambutan', 'NNC'],
 ['loob|NNC', 'loob', 'NNC'],
 ['pagmartilyo|NNC', 'pagmartilyo', 'NNC'],
 ['pagtatanim|NNC', 'pagtatanim', 'NNC'],
 ['tita|NNC', 'tita', 'NNC'],
 ['hinog|NNC', 'hinog', 'NNC'],
 ['aw|NNC', 'aw', 'NNC'],
 ['tagapangasiwa|NNC', 'tagapangasiwa', 'NNC'],
 ['lubak|NNC', 'lubak', 'NNC'],
 ['mama|NNC', 'mama', 'NNC'],
 ['copyright|NNC', 'copyright', 'NNC'],
 ['kumpol|NNC', 'kumpol', 'NNC'],
 ['pamasahe|NNC', 'pamasahe', 'NNC'],
 ['benta|NNC', 'benta', 'NNC'],
 ['buhol|NNC', 'buhol', 'NNC'],
 ['single.letsreadasia.org|NNC', 'single.letsreadasia.org', 'NNC'],
 ['uka|NNC', 'uka', 'NNC'],
 ['giniginaw|NNC', 'giniginaw', 'NNC'],
 ['kadena|NNC', 'kadena', 'NNC'],
 ['pelican|NNC', 'pelican', 'NNC'],
 ['traysikel|NNC', 'traysikel', 'NNC'],
 ['barbero|NNC', 'barbero', 'NNC'],
 ['pakete|NNC', 'pakete', 'NNC'],
 ['kahugis|NNC', 'kahugis', 'NNC'],
 ['hirap|NNC', 'hirap', 'NNC'],
 ['bisa|NNC', 'bisa', 'NNC'],
 ['paligi|NNC', 'paligi', 'NNC'],
 ['konsepto|NNC', 'konsepto', 'NNC'],
 ['paghahamon|NNC', 'paghahamon', 'NNC'],
 ['turo|NNC', 'turo', 'NNC'],
 ['atnakatatakot|NNC', 'atnakatatakot', 'NNC'],
 ['katawanIto|NNC', 'katawanIto', 'NNC'],
 ['ilahas|NNC', 'ilahas', 'NNC'],
 ['uusap|NNC', 'uusap', 'NNC'],
 ['sibat|NNC', 'sibat', 'NNC'],
 ['basa|NNC', 'basa', 'NNC'],
 ['bayong|NNC', 'bayong', 'NNC'],
 ['tatay|NNC', 'tatay', 'NNC'],
 ['kambal|NNC', 'kambal', 'NNC'],
 ['pagbabangayan|NNC', 'pagbabangayan', 'NNC'],
 ['korona|NNC', 'korona', 'NNC'],
 ['pagkawala|NNC', 'pagkawala', 'NNC'],
 ['pagsasama|NNC', 'pagsasama', 'NNC'],
 ['kalidad|NNC', 'kalidad', 'NNC'],
 ['tiyan|NNC', 'tiyan', 'NNC'],
 ['kubo|NNC', 'kubo', 'NNC'],
 ['Neema|NNC', 'Neema', 'NNC'],
 ['samot|NNC', 'samot', 'NNC'],
 ['Hi|NNC', 'Hi', 'NNC'],
 ['hatian|NNC', 'hatian', 'NNC'],
 ['konsentrasyon|NNC', 'konsentrasyon', 'NNC'],
 ['paggigitara|NNC', 'paggigitara', 'NNC'],
 ['pagdating|NNC', 'pagdating', 'NNC'],
 ['mayiba|NNC', 'mayiba', 'NNC'],
 ['pabalat|NNC', 'pabalat', 'NNC'],
 ['alon|NNC', 'alon', 'NNC'],
 ['pamimitas|NNC', 'pamimitas', 'NNC'],
 ['aytumakbo|NNC', 'aytumakbo', 'NNC'],
 ['bukaran|NNC', 'bukaran', 'NNC'],
 ['Ama|NNC', 'Ama', 'NNC'],
 ['pansin|NNC', 'pansin', 'NNC'],
 ['basketbol|NNC', 'basketbol', 'NNC'],
 ['boses|NNC', 'boses', 'NNC'],
 ['sando|NNC', 'sando', 'NNC'],
 ['kabab|NNC', 'kabab', 'NNC'],
 ['petsa|NNC', 'petsa', 'NNC'],
 ['inom|NNC', 'inom', 'NNC'],
 ['reptilya|NNC', 'reptilya', 'NNC'],
 ['pra|NNC', 'pra', 'NNC'],
 ['magbibihis|NNC', 'magbibihis', 'NNC'],
 ['pamamaraan|NNC', 'pamamaraan', 'NNC'],
 ['mundo|NNC', 'mundo', 'NNC'],
 ['karakter|NNC', 'karakter', 'NNC'],
 ['alupihan|NNC', 'alupihan', 'NNC'],
 ['itik|NNC', 'itik', 'NNC'],
 ['tanod|NNC', 'tanod', 'NNC'],
 ['tagubilinSiya|NNC', 'tagubilinSiya', 'NNC'],
 ['Litrato|NNC', 'Litrato', 'NNC'],
 ['Tongtong|NNC', 'Tongtong', 'NNC'],
 ['sanhi|NNC', 'sanhi', 'NNC'],
 ['esplanade|NNC', 'esplanade', 'NNC'],
 ['pagluluto|NNC', 'pagluluto', 'NNC'],
 ['oyayi|NNC', 'oyayi', 'NNC'],
 ['manok|NNC', 'manok', 'NNC'],
 ['tuka|NNC', 'tuka', 'NNC'],
 ['pagbukud|NNC', 'pagbukud', 'NNC'],
 ['tsart|NNC', 'tsart', 'NNC'],
 ['Salaan|NNC', 'Salaan', 'NNC'],
 ['kahihinatnan|NNC', 'kahihinatnan', 'NNC'],
 ['artista|NNC', 'artista', 'NNC'],
 ['pamingwit|NNC', 'pamingwit', 'NNC'],
 ['dibdib|NNC', 'dibdib', 'NNC'],
 ['pridyeder|NNC', 'pridyeder', 'NNC'],
 ['hapon|NNC', 'hapon', 'NNC'],
 ['pagpasok|NNC', 'pagpasok', 'NNC'],
 ['presidente|NNC', 'presidente', 'NNC'],
 ['saway|NNC', 'saway', 'NNC'],
 ['pataas|NNC', 'pataas', 'NNC'],
 ['kawit|NNC', 'kawit', 'NNC'],
 ['는것을아주좋아합니다|NNC', '는것을아주좋아합니다', 'NNC'],
 ['imbakan|NNC', 'imbakan', 'NNC'],
 ['retrato|NNC', 'retrato', 'NNC'],
 ['timbang|NNC', 'timbang', 'NNC'],
 ['Inay|NNC', 'Inay', 'NNC'],
 ['program|NNC', 'program', 'NNC'],
 ['chainsaw|NNC', 'chainsaw', 'NNC'],
 ['keyk|NNC', 'keyk', 'NNC'],
 ['iiba|NNC', 'iiba', 'NNC'],
 ['Bulwagan|NNC', 'Bulwagan', 'NNC'],
 ['parada|NNC', 'parada', 'NNC'],
 ['tagapagsaayos|NNC', 'tagapagsaayos', 'NNC'],
 ['bisig|NNC', 'bisig', 'NNC'],
 ['pagpapaunlad|NNC', 'pagpapaunlad', 'NNC'],
 ['ere|NNC', 'ere', 'NNC'],
 ['galak|NNC', 'galak', 'NNC'],
 ['maiilap|NNC', 'maiilap', 'NNC'],
 ['manggagamot|NNC', 'manggagamot', 'NNC'],
 ['bangin|NNC', 'bangin', 'NNC'],
 ['kaba|NNC', 'kaba', 'NNC'],
 ['koloretom|NNC', 'koloretom', 'NNC'],
 ['karamdaman|NNC', 'karamdaman', 'NNC'],
 ['paglubog|NNC', 'paglubog', 'NNC'],
 ['lobo|NNC', 'lobo', 'NNC'],
 ['aaral|NNC', 'aaral', 'NNC'],
 ['pagtagaktak|NNC', 'pagtagaktak', 'NNC'],
 ['buwaya|NNC', 'buwaya', 'NNC'],
 ['damo|NNC', 'damo', 'NNC'],
 ['pamatay|NNC', 'pamatay', 'NNC'],
 ['kaibiganSigner|NNC', 'kaibiganSigner', 'NNC'],
 ['data|NNC', 'data', 'NNC'],
 ['alpabeto|NNC', 'alpabeto', 'NNC'],
 ['alisan|NNC', 'alisan', 'NNC'],
 ['gabi|NNC', 'gabi', 'NNC'],
 ['Ulap|NNC', 'Ulap', 'NNC'],
 ['oopera|NNC', 'oopera', 'NNC'],
 ['lason|NNC', 'lason', 'NNC'],
 ['Tenga|NNC', 'Tenga', 'NNC'],
 ['kumulog|NNC', 'kumulog', 'NNC'],
 ['ampunan|NNC', 'ampunan', 'NNC'],
 ['taka|NNC', 'taka', 'NNC'],
 ['pool|NNC', 'pool', 'NNC'],
 ['litratista|NNC', 'litratista', 'NNC'],
 ['layag|NNC', 'layag', 'NNC'],
 ['labas|NNC', 'labas', 'NNC'],
 ['bakyum|NNC', 'bakyum', 'NNC'],
 ['atensiyon|NNC', 'atensiyon', 'NNC'],
 ['kabarangay|NNC', 'kabarangay', 'NNC'],
 ['tagtuyot|NNC', 'tagtuyot', 'NNC'],
 ['tinapay|NNC', 'tinapay', 'NNC'],
 ['didikit|NNC', 'didikit', 'NNC'],
 ['pagsakay|NNC', 'pagsakay', 'NNC'],
 ['lutuin|NNC', 'lutuin', 'NNC'],
 ['okasyon|NNC', 'okasyon', 'NNC'],
 ['pagsasaayos|NNC', 'pagsasaayos', 'NNC'],
 ['alang|NNC', 'alang', 'NNC'],
 ['tava|NNC', 'tava', 'NNC'],
 ['baho|NNC', 'baho', 'NNC'],
 ['lulusong|NNC', 'lulusong', 'NNC'],
 ['noo|NNC', 'noo', 'NNC'],
 ['bandana|NNC', 'bandana', 'NNC'],
 ['yantok|NNC', 'yantok', 'NNC'],
 ['silapatungo|NNC', 'silapatungo', 'NNC'],
 ['minatamis|NNC', 'minatamis', 'NNC'],
 ['pagmamay|NNC', 'pagmamay', 'NNC'],
 ['sabat|NNC', 'sabat', 'NNC'],
 ['isusuot|NNC', 'isusuot', 'NNC'],
 ['miryenda|NNC', 'miryenda', 'NNC'],
 ['pintor|NNC', 'pintor', 'NNC'],
 ['patong|NNC', 'patong', 'NNC'],
 ['pananaliksik|NNC', 'pananaliksik', 'NNC'],
 ['talì|NNC', 'talì', 'NNC'],
 ['hagikhik|NNC', 'hagikhik', 'NNC'],
 ['khyak|NNC', 'khyak', 'NNC'],
 ['ginto|NNC', 'ginto', 'NNC'],
 ['taong|NNC', 'taong', 'NNC'],
 ['buwan|NNC', 'buwan', 'NNC'],
 ['buwitre|NNC', 'buwitre', 'NNC'],
 ['pagpayag|NNC', 'pagpayag', 'NNC'],
 ['katapangan|NNC', 'katapangan', 'NNC'],
 ['halina|NNC', 'halina', 'NNC'],
 ['alalang|NNC', 'alalang', 'NNC'],
 ['daliri|NNC', 'daliri', 'NNC'],
 ['sakapaligiran|NNC', 'sakapaligiran', 'NNC'],
 ['bangko|NNC', 'bangko', 'NNC'],
 ['paraan|NNC', 'paraan', 'NNC'],
 ['inay|NNC', 'inay', 'NNC'],
 ['kasiguraduhan|NNC', 'kasiguraduhan', 'NNC'],
 ['kuna|NNC', 'kuna', 'NNC'],
 ['paglipas|NNC', 'paglipas', 'NNC'],
 ['singko|NNC', 'singko', 'NNC'],
 ['pagdrowing|NNC', 'pagdrowing', 'NNC'],
 ['kumpanya|NNC', 'kumpanya', 'NNC'],
 ['hulihan|NNC', 'hulihan', 'NNC'],
 ['layang|NNC', 'layang', 'NNC'],
 ['mapula|NNC', 'mapula', 'NNC'],
 ['hakbang|NNC', 'hakbang', 'NNC'],
 ['matirhan|NNC', 'matirhan', 'NNC'],
 ['pagkabata|NNC', 'pagkabata', 'NNC'],
 ['sitaw|NNC', 'sitaw', 'NNC'],
 ['mamumutol|NNC', 'mamumutol', 'NNC'],
 ['musang|NNC', 'musang', 'NNC'],
 ['turista|NNC', 'turista', 'NNC'],
 ['eskenita|NNC', 'eskenita', 'NNC'],
 ['nikel|NNC', 'nikel', 'NNC'],
 ['patutunguhan|NNC', 'patutunguhan', 'NNC'],
 ['pugita|NNC', 'pugita', 'NNC'],
 ['paghuli|NNC', 'paghuli', 'NNC'],
 ['hahapunan|NNC', 'hahapunan', 'NNC'],
 ['papelastik|NNC', 'papelastik', 'NNC'],
 ['balahibo|NNC', 'balahibo', 'NNC'],
 ['kakayanan|NNC', 'kakayanan', 'NNC'],
 ['pagkathaan|NNC', 'pagkathaan', 'NNC'],
 ['lulan|NNC', 'lulan', 'NNC'],
 ['bulaklak|NNC', 'bulaklak', 'NNC'],
 ['gusali|NNC', 'gusali', 'NNC'],
 ['panloloko|NNC', 'panloloko', 'NNC'],
 ['kapaligiran|NNC', 'kapaligiran', 'NNC'],
 ['patubigan|NNC', 'patubigan', 'NNC'],
 ['ipin|NNC', 'ipin', 'NNC'],
 ['Itlog|NNC', 'Itlog', 'NNC'],
 ['hukbo|NNC', 'hukbo', 'NNC'],
 ['salusalo|NNC', 'salusalo', 'NNC'],
 ['bota|NNC', 'bota', 'NNC'],
 ['Isda|NNC', 'Isda', 'NNC'],
 ['paglalakbay|NNC', 'paglalakbay', 'NNC'],
 ['Tubig|NNC', 'Tubig', 'NNC'],
 ['bigla|NNC', 'bigla', 'NNC'],
 ['paglilinis|NNC', 'paglilinis', 'NNC'],
 ['likha|NNC', 'likha', 'NNC'],
 ['mensahe|NNC', 'mensahe', 'NNC'],
 ['cartoon|NNC', 'cartoon', 'NNC'],
 ['silya|NNC', 'silya', 'NNC'],
 ['tropeyo|NNC', 'tropeyo', 'NNC'],
 ['pagkasakim|NNC', 'pagkasakim', 'NNC'],
 ['bida|NNC', 'bida', 'NNC'],
 ['matatanda|NNC', 'matatanda', 'NNC'],
 ['talim|NNC', 'talim', 'NNC'],
 ['sasakyan|NNC', 'sasakyan', 'NNC'],
 ['liksi|NNC', 'liksi', 'NNC'],
 ['taglagas|NNC', 'taglagas', 'NNC'],
 ['tubi|NNC', 'tubi', 'NNC'],
 ['pailawan|NNC', 'pailawan', 'NNC'],
 ['pagtitipon|NNC', 'pagtitipon', 'NNC'],
 ['babati|NNC', 'babati', 'NNC'],
 ['modyul|NNC', 'modyul', 'NNC'],
 ['kuyog|NNC', 'kuyog', 'NNC'],
 ['bahay.at|NNC', 'bahay.at', 'NNC'],
 ['pauwi|NNC', 'pauwi', 'NNC'],
 ['balkonahe|NNC', 'balkonahe', 'NNC'],
 ['yungib|NNC', 'yungib', 'NNC'],
 ['kalakal|NNC', 'kalakal', 'NNC'],
 ['takipsilim|NNC', 'takipsilim', 'NNC'],
 ['tili|NNC', 'tili', 'NNC'],
 ['ubas|NNC', 'ubas', 'NNC'],
 ['bughaw|NNC', 'bughaw', 'NNC'],
 ['pagbabala|NNC', 'pagbabala', 'NNC'],
 ['singhot|NNC', 'singhot', 'NNC'],
 ['usbong|NNC', 'usbong', 'NNC'],
 ['ube|NNC', 'ube', 'NNC'],
 ['pala|NNC', 'pala', 'NNC'],
 ['kapsula|NNC', 'kapsula', 'NNC'],
 ['binhi|NNC', 'binhi', 'NNC'],
 ['nganga|NNC', 'nganga', 'NNC'],
 ['patatas|NNC', 'patatas', 'NNC'],
 ['gutóm|NNC', 'gutóm', 'NNC'],
 ['mamahalin|NNC', 'mamahalin', 'NNC'],
 ['gapang|NNC', 'gapang', 'NNC'],
 ['dyan|NNC', 'dyan', 'NNC'],
 ['taya|NNC', 'taya', 'NNC'],
 ['edad|NNC', 'edad', 'NNC'],
 ['sitalunan|NNC', 'sitalunan', 'NNC'],
 ['isda|NNC', 'isda', 'NNC'],
 ['Tungkulin|NNC', 'Tungkulin', 'NNC'],
 ['supot|NNC', 'supot', 'NNC'],
 ['kadiliman|NNC', 'kadiliman', 'NNC'],
 ['kumikislap|NNC', 'kumikislap', 'NNC'],
 ['basurangito|NNC', 'basurangito', 'NNC'],
 ['양한경험을이어왔습니다|NNC', '양한경험을이어왔습니다', 'NNC'],
 ['pambomba|NNC', 'pambomba', 'NNC'],
 ['pigura|NNC', 'pigura', 'NNC'],
 ['paglipat|NNC', 'paglipat', 'NNC'],
 ['kukis|NNC', 'kukis', 'NNC'],
 ['bangkota|NNC', 'bangkota', 'NNC'],
 ['lohika|NNC', 'lohika', 'NNC'],
 ['pangangalaga|NNC', 'pangangalaga', 'NNC'],
 ['pagitan|NNC', 'pagitan', 'NNC'],
 ['pananagutan|NNC', 'pananagutan', 'NNC'],
 ['pahinga|NNC', 'pahinga', 'NNC'],
 ['pagpapatnubay|NNC', 'pagpapatnubay', 'NNC'],
 ['Iyak|NNC', 'Iyak', 'NNC'],
 ['tuntungan|NNC', 'tuntungan', 'NNC'],
 ['tulog|NNC', 'tulog', 'NNC'],
 ['tiyakadOkey|NNC', 'tiyakadOkey', 'NNC'],
 ['atlaruan|NNC', 'atlaruan', 'NNC'],
 ['putikan|NNC', 'putikan', 'NNC'],
 ['pagtataas|NNC', 'pagtataas', 'NNC'],
 ['hudyat|NNC', 'hudyat', 'NNC'],
 ['kulantro|NNC', 'kulantro', 'NNC'],
 ['tirador|NNC', 'tirador', 'NNC'],
 ['Reklamo|NNC', 'Reklamo', 'NNC'],
 ['suporta|NNC', 'suporta', 'NNC'],
 ['hiwa|NNC', 'hiwa', 'NNC'],
 ['Nimo|NNC', 'Nimo', 'NNC'],
 ['maskara|NNC', 'maskara', 'NNC'],
 ['kabutihan|NNC', 'kabutihan', 'NNC'],
 ['petchay|NNC', 'petchay', 'NNC'],
 ['bote|NNC', 'bote', 'NNC'],
 ['pansulat|NNC', 'pansulat', 'NNC'],
 ['uulan|NNC', 'uulan', 'NNC'],
 ['atis|NNC', 'atis', 'NNC'],
 ['taginit|NNC', 'taginit', 'NNC'],
 ['putahe|NNC', 'putahe', 'NNC'],
 ['premyo|NNC', 'premyo', 'NNC'],
 ['pagaaral|NNC', 'pagaaral', 'NNC'],
 ['tawanan|NNC', 'tawanan', 'NNC'],

Compare the vocabulary of the translated top-down to the letsreadasia top down

In [4]:
import pandas as pd

lra_df = pd.read_csv("Organized_Text_data/vocabulary_letsreadasia.csv").drop(columns='Unnamed: 0')
assessed_tl_lemma_df = pd.read_json("Organized_Text_data/assessed_dp_back_translation_filtered.json")[['just_category', 'probable_nsubj']].drop_duplicates()
assessed_tl_lemma_df['probable_nsubj'] = assessed_tl_lemma_df['probable_nsubj'].str.lower()
assessed_tl_lemma_df

      just_category probable_nsubj
1      organization          lupon
2             event       pag-awit
3            animal       aardvark
4            animal           pusa
5            animal        abalone
...             ...            ...
14712        object            xyy
14727        person         yemeni
14787        object          zooid
14789        person        soologo
14793        object    zooplankton

[8913 rows x 2 columns]

In [5]:
groupby_categ = assessed_tl_lemma_df.groupby('just_category')
groupby_categ = groupby_categ.agg(list)
#groupby_categ = groupby_categ.reset_index()
categ_dict = groupby_categ.to_dict()['probable_nsubj']

for key in categ_dict:
    new_val = set(categ_dict[key])
    categ_dict[key] = new_val

categ_dict.keys()

dict_keys(['administration', 'aim', 'animal', 'consequence', 'event', 'location', 'object', 'organization', 'person'])

In [6]:
groupby_lemma = assessed_tl_lemma_df.groupby('probable_nsubj')
groupby_lemma = groupby_lemma.agg(list)
groupby_lemma = groupby_lemma.reset_index()
groupby_lemma['lemma'] = groupby_lemma['probable_nsubj']

groupby_lemma.loc[groupby_lemma['just_category'].str.len() > 1]

,probable_nsubj,just_category,lemma
0,,"[object, person, event, animal, organization, ...",
1,-,"[event, person, animal, organization, object]",-
5,aabuso,"[person, event]",aabuso
8,aakit,"[object, person]",aakit
12,aaliw,"[object, person]",aaliw
...,...,...,...
7491,zionista,"[object, person]",zionista
7493,zodiac,"[location, object]",zodiac
7497,zoophyte,"[animal, object]",zoophyte
7498,zooplankton,"[animal, object]",zooplankton
7500,zulu,"[object, person]",zulu

In [6]:
lra_df['lemma'] = lra_df['lemma'].str.lower()
common_nouns = lra_df.loc[lra_df['postag'].str.contains('NN')][['tokens','lemma']]
common_nouns

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [8]:
# merge on lemma
assessed_in_vocab = common_nouns.merge(groupby_lemma,on='lemma',how='inner' )
assessed_in_vocab

,tokens,lemma,probable_nsubj,just_category
0,pamilihan|NNC,pamilihan,pamilihan,"[event, organization]"
1,abala|NNC,abala,abala,"[object, organization, person, event]"
2,turo|NNC,turo,turo,[event]
3,Turo|NNP,turo,turo,[event]
4,INHINYERO|NNC,inhinyero,inhinyero,"[object, person]"
...,...,...,...,...
705,bukirin|NNC,bukirin,bukirin,"[location, object]"
706,ingay|NNC,ingay,ingay,[event]
707,arkitekto|NNC,arkitekto,arkitekto,"[object, person]"
708,plaza|NNC,plaza,plaza,"[location, object]"
709,tipaklong|NNC,tipaklong,tipaklong,[animal]

In [7]:
common_nouns_categorized = pd.concat([common_nouns,assessed_in_vocab]).drop_duplicates(subset='tokens',keep='last')
common_nouns_categorized['just_category'] = common_nouns_categorized['just_category'].fillna('MISC')
common_nouns_categorized = common_nouns_categorized[['tokens','lemma','just_category']]
#common_nouns_categorized

# split into MISCs, multitags, and neither
miscs_categorized = common_nouns_categorized.loc[common_nouns_categorized['just_category'] == 'MISC']
non_misc = common_nouns_categorized.loc[common_nouns_categorized['just_category'] != 'MISC'] #guaranteed list
multitag_categorized = non_misc.loc[non_misc['just_category'].str.len() > 1]
neither_categorized = non_misc.loc[non_misc['just_category'].str.len() <= 1]

# UPDATE 1 - first batch of manually annotated MISCs
misc_manual_1 = pd.read_csv("./Organized_text_data/misc_manual_add_1.csv")[['tokens','manual_tag']]
misc_manual_1['manual_tag'] = misc_manual_1['manual_tag'].apply(lambda x:x.split(','))

misc_update = misc_manual_1.merge(miscs_categorized,on='tokens',how='right')
misc_update = misc_update.fillna('MISC')
misc_update['just_category'] = misc_update['manual_tag']
misc_update = misc_update.drop(columns=['manual_tag'])

## UPDATE 2 - first batch of manually annotated multitags
multitag_manual_1 = pd.read_csv("./Organized_text_data/multitag_manual_add_1.csv")[['tokens','manual_tag']]
multitag_manual_1['manual_tag'] = multitag_manual_1['manual_tag'].apply(lambda x:x.split(','))

multitag_update = multitag_manual_1.merge(multitag_categorized,on='tokens',how='right')
multitag_update['just_category'] = multitag_update['manual_tag']
multitag_update = multitag_update.drop(columns=['manual_tag'])

#non_misc
non_misc = misc_manual_1.merge(neither_categorized,on='tokens',how='right')
non_misc = non_misc.loc[non_misc['just_category'] != 'MISC']
non_misc = non_misc.drop(columns=['manual_tag'])

common_nouns_categorized = pd.concat([misc_update, multitag_update, non_misc]).reset_index().drop(columns='index')
common_nouns_categorized.to_json("./Organized_text_data/manual_assessed_1.json")
common_nouns_categorized

NameError: name 'common_nouns' is not defined

In [1]:
import pandas as pd
common_nouns_categorized = pd.read_json("./Organized_text_data/manual_assessed_1.json")
common_nouns_categorized

               tokens        lemma just_category
0             One|NNP          one      [no_tag]
1        alikabok|NNC     alikabok      [object]
2            Asan|NNP         asan      [no_tag]
3           uulan|NNC        uulan       [event]
4          pansin|NNC       pansin          MISC
...               ...          ...           ...
3227         puno|NNC         puno      [object]
3228  pangingisda|NNC  pangingisda       [event]
3229     pagsukat|NNC     pagsukat       [event]
3230        ingay|NNC        ingay       [event]
3231    tipaklong|NNC    tipaklong      [animal]

[3232 rows x 3 columns]

In [ ]:
multitag_manual_1 = pd.read_csv("./Organized_text_data/multitag_manual_add_1.csv")[['tokens','manual_tag']]
multitag_manual_1['manual_tag'] = multitag_manual_1['manual_tag'].apply(lambda x:x.split(','))

              tokens            manual_tag
0          kagat|NNC              [gerund]
1        tilapya|NNC                [food]
2            ani|NNC              [object]
3    pagkabahala|NNC             [emotion]
4          dilim|NNC  [location, abstract]
..               ...                   ...
243       kausap|NNC              [person]
244          ulo|NNC           [body part]
245       kabayo|NNC              [animal]
246         Anak|NNC              [person]
247          uod|NNC              [animal]

[248 rows x 2 columns]

In [ ]:
misc_list = common_nouns_categorized.loc[common_nouns_categorized['just_category']=='MISC']
#misc_list[['tokens','just_category']].loc[misc_list['tokens'].apply(lambda x:x[0]).str.isupper()] #tokens first letter is uppercase
#misc_list['tokens'].values.to('Organized_Text_data/noun_tokens_misc.txt')
misc_list

In [2]:
multitags = common_nouns_categorized.loc[(common_nouns_categorized['just_category'].str.len() > 1) & (common_nouns_categorized['just_category']!='MISC')]

multitags[['tokens', 'just_category']].to_clipboard()#csv('Organized_Text_data/noun_tokens_multitags.txt')
multitags

              tokens       lemma            just_category
166      disenyo|NNC     disenyo           [MISC, person]
177         saya|NNC        saya        [no_tag, emotion]
186      paalala|NNC     paalala           [no_tag, MISC]
192         iyak|NNC        iyak         [no_tag, gerund]
203      hapunan|NNC     hapunan            [food, event]
...              ...         ...                      ...
2717      daanan|NNC      daanan       [location, no_tag]
2726  paglalakad|NNC  paglalakad         [gerund, no_tag]
2729    pelikula|NNC    pelikula  [event,  object,  MISC]
2732        apoy|NNC        apoy         [event,  object]
2737       plaza|NNC       plaza      [location,  object]

[83 rows x 3 columns]

In [ ]:
common_nouns_categorized.loc[(common_nouns_categorized['just_category'].str.len() <= 1) & (common_nouns_categorized['just_category']!='MISC')]

In [13]:
# MISC token how it is used in sentences
import json

sentence_corpus = open("./postagging/textAllFil_postagged_FINAL.txt",'r')
sentences = sentence_corpus.readlines()
sentence_corpus.close()

set_list = []

for sentence in sentences:
    q = set(sentence.split()) # turns into a set of words
    i = {'tokenset' : q, 'sentence' : sentence}
    set_list.append(i)

misc_examples = {}
for misc_token in misc_list['tokens'].values.tolist():
    a = []
    for i in set_list:
        if misc_token in i['tokenset']:
            a.append(i['sentence'])
    misc_examples[misc_token] = a

multitag_examples = {}
for multitag_token in multitags['tokens'].values.tolist():
    a = []
    for i in set_list:
        if multitag_token in i['tokenset']:
            a.append(i['sentence'])
    multitag_examples[multitag_token] = a

# Convert and write JSON object to file
with open("./Organized_text_data/misc_examples.json", "w") as outfile: 
    json.dump(misc_examples, outfile)

In [34]:
multitag_examples['abala|NNC']

['Ang|DTC aming|PRSP_CCP mga|DTCP kapitbahay|NNC ay|LM abala|NNC sa|CCT paggawa|NNC ng|CCB makulay|JJD na|CCP tarangkahan|NNC upang|CCB ipagdiwang|VBOB ang|DTC Araw|NNP ng|CCB Kalayaan|NNP .|PMP\n',
 'Wala|VBN kasi|CCR siyang|PRS_CCP kasama|CCB sa|CCT bahay|NNC nila|PRP ,|PMC dahil|CCR abalang|NNC_CCP -|PMS abala|NNC ang|DTC mga|DTCP magulang|NNC niya|PRS .|PMP\n',
 'Di|RBF maibibigay|VBTF sa|CCT anak|NNC kung|CCR parehong|JJC_CCP di|RBF nariyan|VBTS ,|PMC mga|DTCP magulang|NNC na|CCP abala|NNC sa|CCT trabaho|NNC palagi|RBW .|PMP\n',
 '"|PMS Huwag|RBF kanang|JJD_CCP mag|VBW -|PMS abala|NNC ,|PMC "|PMS sabi|VBS ng|CCB lalaki|NNC .|PMP  \n']

In [318]:
# RUN THIS FIRST
import json
misc_examples = {}
with open("./Organized_text_data/misc_examples.json", 'r') as f:
    misc_examples = json.loads(f.read())
#misc_examples

In [ ]:
# run this with the token as a key to get the reference sentences
misc_examples['barangay|NNC']

filling up the misc_tags for now

In [69]:
import pandas as pd

misc_manual_1 = pd.read_csv("./Organized_text_data/misc_manual_add_1.csv")[['tokens','manual_tag']]
misc_manual_1['manual_tag'] = misc_manual_1['manual_tag'].apply(lambda x:x.split(','))
misc_manual_1['just_category'] = misc_manual_1['manual_tag']
misc_manual_1 = misc_manual_1.drop(columns='manual_tag')
misc_manual_1 = misc_manual_1.explode('just_category')
misc_manual_1

                tokens just_category
0            Iraga|NNP        no_tag
1     pagpapaunlad|NNC         event
2             Mang|NNP        no_tag
3         kalabasa|NNC          food
4             Sita|NNP        no_tag
...                ...           ...
1351         LEAD|NNPA        no_tag
1352       Simatar|NNP        no_tag
1353          Buhi|NNP        no_tag
1354        Neeeey|NNP        no_tag
1355   Kumakaripas|NNP        no_tag

[1389 rows x 2 columns]

In [ ]:
common_noun_categorized_updated = misc_manual_1.merge(common_nouns_categorized.explode('just_category'),how='right',on=['tokens','just_category']).drop_duplicates()
common_noun_categorized_updated = common_noun_categorized_updated.groupby(['tokens','lemma']).agg(list)
common_noun_categorized_updated = common_noun_categorized_updated.reset_index()
common_noun_categorized_updated.to_csv("")
common_noun_categorized_updated

           tokens   lemma   just_category
0          's|NNC      's          [MISC]
1          's|NNP      's          [MISC]
2     ......|NNPA  ......          [MISC]
3      .....|NNPA   .....          [MISC]
4       ....|NNPA    ....          [MISC]
...           ...     ...             ...
3227       yo|NNC      yo          [MISC]
3228      yo|NNCA      yo          [MISC]
3229    yunit|NNC   yunit  [organization]
3230       …|NNCA       …          [MISC]
3231        …|NNP       …          [MISC]

[3232 rows x 3 columns]

In [26]:
common_nouns_categorized

              tokens        lemma             just_category
0            Yay|NNP          yay                      MISC
3     pagdarasal|NNC   pagdarasal                      MISC
10          East|NNP         east                      MISC
12    bulang|NNC_CCP       bulang                      MISC
13   temperatura|NNC  temperatura                      MISC
..               ...          ...                       ...
705          Mam|NNP          mam                  [person]
706          mam|NNC          mam                  [person]
707          uod|NNC          uod  [animal, object, person]
708         Lolo|NNP         lolo                  [person]
709    kaganapan|NNC    kaganapan                   [event]

[3232 rows x 3 columns]