In [ ]:
# add more sentences from the file to the list
sentenceList = []
f = open('textAllFil_postagged_FINAL.txt', 'r')
lines = f.readlines()
f.close()

# gettingQuote = False
# temp_sentence = ""

# for line in lines:
#     #print(line.strip())
#     if '"|PMS' in line:
#         gettingQuote = not gettingQuote
#         temp_sentence+=f'{line.replace('\n', '')} '
#         continue

#     if gettingQuote:
#         temp_sentence+=f'{line.replace('\n', '')} '
#     else:
#         if len(temp_sentence) > 0:
#             sentenceList.append(temp_sentence+' '+line)
#             print(f"{temp_sentence} {line}".strip())
#             temp_sentence = ""
#         else:
#             sentenceList.append(line)

"|PMSPara|CCT lamang|RBI sa|CCT mga|DTCP lalaking|NNC_CCP kuliglig|JJD ang|DTC paligsahang|NNC_CCP ito|PRO at|CCA hindi|RBF sa|CCT mga|DTCP babae|NNC ,|PMC "|PMS  sabi|VBS ni|DTP pinunong|NNC_CCP kuliglig|JJD .|PMP
"|PMS Hindi|RBF tama|RBT ito|PRO !|PMQ Mabilis|RBD din|RBI akong|PRS_CCP lumipad|VBAF !|PMQ Masdan|VBTF ninyo|PRP !|PMS "|PMSDali|NNP -|PMS daling|FW bumuwelo|FW si|DTP Tori|NNP ngunit|CCT siya|PRS ay|LM natisod|VBTS at|CCA tuluyang|RBD_CCP nahulog|VBTS .|PMP "|PMSArayyyyyyyy|NNP !|PMS "|PMSsigaw|NNC ni|DTP Tori|NNP .|PMP  Biglang|RBD_CCP nagtawanan|VBTS ang|DTC lahat|PRI ng|CCB mgalalaking|JJD_CCP kuliglig|NNC .|PMP
"|PMSItay|NNP ,|PMC maaari|VBS po|RBS bang|RBI_CCP turuan|VBOF ninyo|PRP akong|PRS_CCP lumipad|VBAF nang|RBD mabilis|RBD ?|PMQ "|PMS  Mag|NNP -|PMS aral|NNC ka|PRS na|RBI lang|RBI umawit|VBAF ,|PMC Tori|NNP ,|PMC
"|PMS tugon|NNC ng|CCB kaniyang|PRSP_CCP ama|NNC .|PMP "|PMSInay|NNP ,|PMC nais|VBS ko|PRS pong|PRO_CCP sumali|VBAF sa|CCT pabilisan|NNC sa|CCT paglipad|NNC ,|PMC "|PMS pilit|RBD ni|DTP Tori|NNP .|PMP "|PMSLalaking|JJD_CCP kuliglig|NNC lamang|RBI ang|DTC sumasali|VBTR_VBAF saganoong|JJD_CCP paligsahan|NNC .|PMP "|PMSMalungkot|JJD si|DTP Tori|NNP sapagkat|CCR walang|VBN_CCP nais|VBS na|CCP tumulong|VBAF sa|CCT kaniya|PRSP .|PMP "|PMSBakit|PRQ hindi|RBF maaaring|RBM sumali|VBAF ang|DTC kababaihan|NNC sa|CCT paligsahan|NNC sa|CCT paglipad|NNC ?|PMQ "|PMStanong|NNC niya|PRS sa|CCT sarili|NNC .|PMP Nagpasya|VBTS si|DTP Tori|NNP na|CCP kumilos|VBAF mag|VBW -|PMS isa|PRI .|PMP Palihim|RBD siyang|PRS_CCP magsasanay|VBAF sa|CCT paglipad|NNC ,|PMC sasali|VBTF sa|CCT paligsahan|NNC ,|PMC at|CCA tuluyang|RBD_CCP magwawagi|VBTF !|PMQ Naging|VBTS mahirap|JJD ang|DTC kaniyang|PRSP_CCP pagsasanay|NNC sa|CCT paglipad|NNC katulad|JJC ng|CCB mga|DTCP nagkakarera|VBTR .|PMP Ang|DTC kaniyang|PRSP_CCP pagod|NNC na|CCP pakpak|NNC ay|LM halos|JJD lumagutok|VBAF sa|CCT malakas|JJD na|CCP hampas|NNC ng|CCB hangin|NNC .|PMP Tila|RBM malapit|JJD na|CCP siyang|PRS_CCP sumuko|VBAF .|PMP Siya|PRS '|PMS y|FW nagpahinga|VBTS saglit|RBW sa|CCT isang|PRI_CCP sanga|NNC ,|PMC saka|CCA siya|PRS may|VBH narinig|VBTS na|CCP tunog|NNC .|PMP "|PMSTsip|NNP !|PMS  Tsip|NNP !|PMS
"|PMSSa|CCT kabilang|CCB panig|NNC ng|CCB lambak|NNC ,|PMC isang|PRI_CCP inang|NNC_CCP ibon|NNC ang|DTC nagtuturo|VBTR sa|CCT kaniyang|PRSP_CCP inakay|VBTS na|CCP lumipad|VBAF .|PMP "|PMSHuwag|RBF kang|PRS_CCP matakot|VBW na|CCP lumipad|NNC ,|PMC "|PMS sabi|VBS ng|CCB inang|NNC_CCP ibon|NNC .|PMP "|PMSMaging|VBW matapang|JJD ka|PRS ,|PMC kayang|RBD_CCP -|PMS kaya|CCR mong|PRS_CCP lumipad|VBAF !|PMS "|PMSAlam|VBS ni|DTP Tori|NNP na|CCP malakas|JJD ang|DTC kaniyang|PRSP_CCP loob|NNC na|CCP sumali|VBAF sa|CCT paligsahan|NNC .|PMP "|PMSKayang|RBD_CCP -|PMS kaya|CCR ko|PRS ito|PRO !|PMS "|PMSsigaw|NNC niya|PRS .|PMP Tumalon|VBAF si|DTP Tori|NNP sa|CCT himpapawid|NNC at|CCA nakauwi|VBTS ng|CCB kanilang|PRSP_CCP tahanan|NNC sa|CCT pinakamabilis|JJCS_JJD na|CCP oras|NNC .|PMP Dumating|VBAF na|RBI ang|DTC takdang|JJD_CCP araw|NNC ng|CCB paligsahan|NNC sa|CCT paglipad|NNC .|PMP Sumingit|VBAF siya|PRS sa|CCT karamihan|PRI .|PMP Walang|VBN_CCP nakapansin|VBTS kay|DTP Tori|NNP sa|CCT simula|RBW ...|PMS Ngunit|CCT ...|PMS Nagulat|VBTS ang|DTC lahat|PRI !|PMQ Si|DTP Tori|NNP ang|DTC nangunguna|VBTR !|PMQ Malapit|JJD nang|RBW makarating|VBW sa|CCT huling|JJD_CCP linya|NNC si|DTP Tori|NNP upang|CCB manalo|VBW .|PMP Ngunit|CCT mayroon|VBH siyang|PRS_CCP nakitang|VBTS_CCP papalapit|JJD na|CCP uwak|NNC ,|PMC gutom|NNC ito|PRO ,|PMC at|CCA nais|VBS dagitin|VBOF ang|DTC kaniyang|PRSP_CCP mga|DTCP kasama|CCB .|PMP "|PMSNaku|NNP !|PMS  Hindi|RBF !|PMS
"|PMSsabi|VBS niya|PRS sa|CCT sarili|NNC .|PMP "|PMSKailangan|VBS kong|PRS_CCP iligtas|VBOF ang|DTC mga|DTCP kapwa|PRI ko|PRS kuliglig|NNC !|PMS "|PMSMatapang|JJD na|CCP lumipad|NNC si|DTP Tori|NNP upang|CCB harapin|VBOF ang|DTC uwak|NNC .|PMP "|PMSHoy|NNP ,|PMC uwak|NNC !|PMS "|PMSsigaw|NNC niya|PRS .|PMP "|PMSHalika|NNP rito|PRL !|PMQ  Ako|PRS ang|DTC hulihin|VBOF mo|PRS !|PMS
"|PMSHinabol|VBOF siya|PRS ng|CCB uwak|NNC ,|PMC habang|RBW tuluyan|RBD ng|CCB may|VBH ibang|PRI_CCP kuliglig|NNC na|CCP nagwagi|VBTS sa|CCT paligsahan|NNC .|PMP Nasira|VBTS ang|DTC pakpak|NNC ni|DTP Tori|NNP nang|RBW makagat|VBW ito|PRO ng|CCB uwak|NNC .|PMP Lumagapak|VBTR_VBAF siya|PRS sa|CCT lupa|NNC malapit|JJD sa|CCT matinik|JJD na|CCP halamanan|NNC .|PMP Muling|RBW_CCP sumalakay|VBAF pababa|JJD ang|DTC uwak|NNC .|PMP Buti|NNP na|CCP lamang|RBI mabilis|RBD nakapagtago|RBD si|DTP Tori|NNP sa|CCT ilalim|JJD ng|CCB halamanan|NNC !|PMS Nagpumilit|VBTS ang|DTC uwak|NNC papunta|VBW sa|CCT matinik|JJD na|CCP halamanan|NNC .|PMP "|PMSKaw|NNP !|PMS  Kaw|NNP !|PMS
"|PMSang|DTC sigaw|NNC ng|CCB uwak|NNC .|PMP Sinubukan|VBTS niyang|PRS_CCP igalaw|VBOF ang|DTC kaniyang|PRSP_CCP mga|DTCP pakpak|NNC ngunit|CCT hindi|RBF na|RBI niya|PRS ito|PRO maikilos|VBW .|PMP Hanggang|RBW sa|CCT tuluyan|RBD nang|RBD nakawala|RBD ang|DTC uwak|NNC sa|CCT matinik|JJD na|CCP halamanan|NNC at|CCA lumipad|VBAF papalayo|RBD .|PMP "|PMSHuwag|RBF ka|PRS nang|RBW babalik|VBTF dito|PRL !|PMS "|PMSsabay|RBD -|PMS sabay|JJD na|CCP sigaw|NNC ng|CCB mga|DTCP kuliglig|NNC .|PMP Isang|PRI_CCP mabait|JJD na|CCP kuliglig|NNC naman|RBI ang|DTC tumulong|VBAF kay|DTP Tori|NNP pabalik|VBW sa|CCT dulo|NNC ng|CCB linya|NNC upang|CCB matapos|VBW niya|PRS ang|DTC paligsahan|NNC .|PMP Nakaabang|VBTS ang|DTC mga|DTCP magulang|NNC ni|DTP Tori|NNP sa|CCT kaniya|PRSP .|PMP Binigyan|VBOF nila|PRP si|DTP Tori|NNP ng|CCB gintong|JJD_CCP tropeyo|NNC .|PMP "|PMSTori|NNP ,|PMC pinatunayan|VBTS mong|PRS_CCP ikaw|PRS ay|LM matalino|JJD ,|PMC mabilis|JJD ,|PMC at|CCA matapang|JJD .|PMP  Ikaw|NNP ang|DTC nagwagi|VBTS !|PMQ
"|PMS Mabuhay|VBW si|DTP Tori|NNP !|PMS "|PMSsigaw|NNC ng|CCB lahat|PRI ng|CCB kuliglig|NNC .|PMP "|PMSMabuhay|VBW ang|DTC matapang|JJD na|CCP si|DTP Tori|NNP !|PMS "|PMSBakit|PRQ ang|DTC ulan|NNC ay|LM nahuhulog|VBTR sa|CCT lupa|NNC ,|PMC samantalang|CCT_CCP ang|DTC usok|NNC ay|LM pumapahimpapawid|VBTR_VBAF ?|PMQ  Bakit|PRQ ang|DTC inahing|VBOF_CCP manok|NNC ay|LM itim|JJD ,|PMC samantalang|CCT_CCP ang|DTC sisiw|NNC nito|PRO '|PMS y|FW puti|JJD ?|PMQ
"|PMSBakit|PRQ mahaba|JJD ang|DTC leeg|NNC mo|PRS ?|PMQ "|PMStanong|NNC niya|PRS .|PMP  Siya|PRS ay|LM mausisa|JJD rin|RBI kay|DTP Rhino|NNP .|PMP
"|PMSBakit|PRQ ang|DTC iyong|PRSP_CCP sungay|NNC ay|LM matalas|JJD ?|PMQ .|PMP Naging|VBTS mausisa|NNC sya|PRS kay|DTP Hippo|NNP .|PMP "|PMSBakit|PRQ namumula|VBTR ang|DTC mata|NNC mo|PRS ?|PMQ "|PMStanong|NNC niya|PRS .|PMP At|CCA siya|PRS ay|LM lalong|JJCC_CCP mausisa|JJD tungkol|RBR kay|DTP buwaya|NNC .|PMP Ano|PRQ ba|RBI ang|DTC kinakain|VBTR ng|CCB buwaya|NNC sa|CCT hapunan|NNC ?|PMQ ,|PMC tanong|NNC niya|PRS .|PMP "|PMSHuwag|RBF na|CCP huwag|RBF kang|PRS_CCP magtatanong|VBTF ng|CCB ganyan|NNC !|PMS "|PMSsabi|VBS ng|CCB kanyang|PRSP_CCP ina|NNC .|PMP Tapos|RBW ay|LM lumayo|VBAF siya|PRS ,|PMC nakasimangot|VBTS .|PMP Mabilis|RBD na|CCP lumipad|VBAF pababa|JJD si|DTP Uwak|NNP sa|CCT batang|JJD_CCP elepante|NNC .|PMP Sundan|VBTF mo|PRS ako|PRS sa|CCT ilog|NNC .|PMP Doon|PRL makikita|VBTF mo|PRS kung|RBK ano|RBQ ang|DTC kinakain|VBTR ng|CCB Buwaya|NNC para|CCT sa|CCT hapunan|NNC ,|PMC tugon|NNC ng|CCB Uwak|NNC .|PMP Kaya|CCR '|PMS t|NNCA sinundan|VBOF ng|CCB batang|JJD_CCP elepante|NNC si|DTP Uwak|NNP pababa|JJD sa|CCT ilog|NNC .|PMP Hinawi|NNP nya|PRS ang|DTC mga|DTCP damo|NNC at|CCA tumayo|VBAF sa|CCT gilid|JJD ng|CCB ilog|NNC .|PMP Tumingin|VBAF sya|PRS sa|CCT tubig|NNC .|PMP Nasaan|VBTS ang|DTC buwaya|NNC ?|PMQ "|PMSKumusta|NNP ,|PMC "|PMS sabi|VBS ng|CCB isang|PRI_CCP bato|NNC na|CCP malapit|JJD sa|CCT tabing|FW ilog|NNC .|PMP "|PMSKumusta|NNP ,|PMC "|PMS sabi|VBS ng|CCB batang|JJD_CCP elepante|NNC .|PMP "|PMSMaaari|VBS mo|PRS bang|RBI_CCP sabihin|VBOF sa|CCT akin|PRSP kung|RBK ano|RBQ ang|DTC kinakain|VBTR ng|CCB Buwaya|NNC para|CCT sa|CCT hapunan|NNC ?|PMQ "|PMStanong|NNC niya|PRS "|PMS  Yumuko|VBOF ka|PRS at|CCA sasabihin|VBTF ko|PRS sayo|PRSP ,|PMC '|PMS sabi|VBS ng|CCB bato|NNC .|PMP
"|PMSMababa|JJD ,|PMC mas|JJCC mababa|JJD ,|PMC "|PMS  sabi|VBS ng|CCB bato|NNC .|PMP
"|PMSKakainin|VBTF ka|PRS ni|DTP Buwaya|NNP para|CCT sa|CCT hapunan|NNC !|PMS "|PMSsabi|VBS ng|CCB Uwak|NNC ,|PMC at|CCA lumipad|VBAF palayo|RBD .|PMP  Napaupo|VBTS ang|DTC batang|JJD_CCP elepante|NNC sa|CCT kanyang|PRSP_CCP malalakas|JJD na|CCP binti|NNC at|CCA hinila|VBOF ang|DTC kanyang|PRSP_CCP ilong|NNC .|PMP
"|PMS blag|FW !|PMS "|PMSsiya|PRS ay|LM tumumba|VBAF .|PMP  Bumalik|VBAF ang|DTC buwaya|NNC sa|CCT tubig|NNC .|PMP
"|PMSSino|PRQ po|RBS ang|DTC makapipigil|VBW sa|CCT kanila|PRSP ?|PMQ "|PMStanong|NNC ni|DTP Miguel|NNP .|PMP "|PMSIkaw|NNP ,|PMC "|PMS  sabi|VBS ng|CCB kaniyang|PRSP_CCP ina|NNC .|PMP
"|PMSAko|PRS po|RBS ?|PMQ "|PMS  Ito|PRO ay|LM laging|RBD_CCP nakasalalay|VBTS sa|CCT atin|PRSP ,|PMC
"|PMS paliwanag|NNC ng|CCB kaniyang|PRSP_CCP ina|NNC .|PMP "|PMSMagpadala|VBAF ka|PRS ng|CCB mensahe|NNC sa|CCT kanila|PRSP .|PMP "|PMSNakahanap|VBTS ng|CCB patpat|NNC si|DTP Miguel|NNP at|CCA nagsulat|VBTS ng|CCB mensahe|NNC sa|CCT buhangin|NNC :|PMS S.|NNPA O.|NNPA S.|NNPA "|PMS  Save|NNP Our|NNP Seas|NNP ,|PMC
"|PMS sabi|VBS ni|DTP Miguel|NNP sa|CCT sarili|NNC .|PMP Ngunit|CCT dumating|VBAF ang|DTC malalaking|JJD_CCP alon|NNC at|CCA inanod|VBTS ang|DTC mga|DTCP salita|NNC .|PMP Paulit|NNP -|PMS ulit|RBW na|CCP isinulat|VBTS ni|DTP Miguel|NNP ang|DTC mensahe|NNC .|PMP Isinulat|VBTS niya|PRS ito|PRO kahit|CCT sa|CCT mga|DTCP damong|NNC_CCP -|PMS dagat|NNC .|PMP Isinulat|VBTS niya|PRS ito|PRO gamit|VBS ang|DTC mga|DTCP sirang|JJD_CCP kabibi|NNC .|PMP Paulit|NNP -|PMS ulit|RBW ding|RBI_CCP inaanod|VBTR ng|CCB mga|DTCP alon|NNC ang|DTC bawat|PRI salita|NNC .|PMP "|PMSWalang|VBN_CCP katuturan|NNC ito|PRO !|PMQ  Walang|VBN_CCP makakakita|VBW sa|CCT mga|DTCP mensahe|NNC ko|PRS ,|PMC
"|PMS panghihina|NNC ni|DTP Miguel|NNP .|PMP "|PMSSubukan|VBOF mo|PRS ulit|RBW ,|PMC "|PMS panghihikayat|JJD ng|CCB kaniyang|PRSP_CCP ina|NNC .|PMP "|PMSMagdasal|NNP ka|PRS at|CCA magtiyaga|VBW .|PMP  Huwag|RBF kang|PRS_CCP titigil|VBTF .|PMP
"|PMSHindi|RBF nagtagal|VBTS ,|PMC may|VBH isang|PRI_CCP makintab|JJD na|CCP itim|JJD na|CCP sasakyan|NNC na|CCP pumarada|VBAF sa|CCT harap|NNC ng|CCB kanilang|PRSP_CCP bahay|NNC .|PMP Dalawang|JJN_CCP lalaking|NNC_CCP naka|RBD -|PMS amerikana|FW at|CCA nakasalaming|VBTS itim|JJD ang|DTC bumaba|VBAF mula|RBW rito|PRL .|PMP "|PMSTuwing|RBW umaga|RBW ,|PMC nagpapalipad|VBTR ng|CCB kaniyang|PRSP_CCP eroplano|NNC ang|DTC aming|PRSP_CCP presidente|NNC sa|CCT tabing|NNC -|PMS dagat|NNC na|CCP ito|PRO .|PMP  Nakikita|VBTR niya|PRS ang|DTC iyong|PRSP_CCP mensahe|NNC sa|CCT buhangin|NNC .|PMP
"|PMSsabi|VBS ng|CCB isa|PRI sa|CCT mga|DTCP lalaki|NNC .|PMP "|PMSPinapunta|VBTS niya|PRS kami|PRP rito|PRL para|CCT malaman|VBW kung|RBK ano|RBQ ang|DTC ibig|VBS sabihin|VBOF ng|CCB S.|NNPA O.|NNPA S.|NNPA "|PMS Sabihin|VBOF po|RBS ninyo|PRP sa|CCT inyong|PRSP_CCP presidente|NNC na|CCP ang|DTC ibig|VBS sabihin|VBOF ng|CCB S.|NNPA O.|NNPA S.|NNPA ay|LM Save|NNP Our|NNP Seas|NNP ,|PMC "|PMS  ang|DTC sabi|VBS ni|DTP Miguel|NNP .|PMP
"|PMSPakisabi|NNP po|RBS ninyo|PRP sa|CCT kaniya|PRSP na|CCP ipatigil|VBOF na|CCP ang|DTC pagtatapon|NNC ng|CCB basura|NNC sa|CCT ilog|NNC .|PMP "|PMS  Ang|DTC ilog|NNC ay|LM humahantong|VBTR_VBAF sa|CCT karagatan|NNC .|PMP
"|PMSUmalis|VBAF ang|DTC mga|DTCP lalaki|NNC at|CCA nagpatuloy|VBTS si|DTP Miguel|NNP sa|CCT pagdarasal|NNC .|PMP Araw|NNP -|PMS araw|NNC ,|PMC isinusulat|VBTR niya|PRS ang|DTC mensahe|NNC sa|CCT buhangin|NNC .|PMP At|CCA araw|NNC -|PMS araw|NNC ,|PMC patuloy|RBD na|CCP dumarating|VBTR_VBAF ang|DTC malalakas|JJD na|CCP alon|NNC at|CCA inaanod|VBTR ang|DTC mga|DTCP salita|NNC .|PMP Isang|PRI_CCP araw|NNC ,|PMC pinakita|VBOF ng|CCB ina|NNC ni|DTP Miguel|NNP ang|DTC pangunahing|JJD_CCP balita|NNC sa|CCT dyaryo|NNC :|PMS KUMPANYA|NNP NG|NNPA PAGMIMINA|NNP NAKUHA|NNPA ANG|NNPA MENSAHE|NNPA .|PMP PAGTAPON|NNPA NG|NNPA KANILANG|NNPA DUMI|NNPA SA|NNPA ILOG|NNPA ITITIGIL|NNPA .|PMP Ngumiti|VBAF si|DTP Miguel|NNP ,|PMC tumakbo|VBAF palabas|NNC sa|CCT dalampasigan|NNC ,|PMC at|CCA nakakita|VBTS ng|CCB isang|PRI_CCP patpat|NNC .|PMP Sumulat|VBAF siya|PRS ng|CCB isang|PRI_CCP bagong|JJD_CCP mensahe|NNC sa|CCT buhangin|NNC :|PMS SALAMATMuling|FW dumating|VBAF ang|DTC mga|DTCP alon|NNC mula|RBL sa|CCT karagatan|NNC at|CCA inanod|VBTS na|CCP muli|RBW ang|DTC bawat|PRI salita|NNC .|PMP Pero|CCT ngayon|RBW ,|PMC dala|JJD -|PMS dala|JJD ng|CCB mga|DTCP alon|NNC ang|DTC mensahe|NNC saan|PRQ man|RBI ito|PRO mapadpad|VBW .|PMP Tuwing|RBW umaga|RBW inaakay|VBTR ng|CCB langgam|NNC ang|DTC kawan|NNC ng|CCB anay|NNC sa|CCT mga|DTCP berdeng|JJD_CCP halaman|NNC .|PMP Uminom|VBAF ang|DTC anay|NNC mula|RBL sa|CCT malasa|JJD at|CCA makatas|JJD na|CCP halaman|NNC hanggang|RBW sa|CCT sila|PRP ay|LM mabusog|JJD .|PMP Kaya|CCR ang|DTC mga|DTCP anay|NNC ay|LM nagpakita|VBTS ng|CCB pasasalamat|RBS sa|CCT mga|DTCP langgam|NNC araw|RBW at|CCA gabi|RBW .|PMP Ang|DTC mga|DTCP anay|NNC na|CCP ito|PRO ay|LM bulag|JJD ,|PMC at|CCA kung|CCR wala|VBN ang|DTC mga|DTCP langgam|NNC ay|LM hindi|RBF nila|PRP maabot|VBW ang|DTC mga|DTCP halaman|NNC at|CCA mapawi|VBW ang|DTC kanilang|PRSP_CCP uhaw|NNC .|PMP Pinoprotektahan|VBTR din|RBI ng|CCB mga|DTCP langgam|NNC ang|DTC mga|DTCP anay|NNC mula|RBL sa|CCT mga|DTCP kulisap|NNC .|PMP Ang|DTC mga|DTCP anay|NNC ay|LM may|VBH maikling|JJD_CCP pakpak|NNC .|PMP Hindi|RBF nila|PRP magagawang|VBTF_CCP lumipad|VBAF palayo|RBD sa|CCT mga|DTCP kulisap|NNC kapag|CCR umatake|VBAF sila|PRP .|PMP Kaya|CCR naman|RBI ,|PMC ang|DTC mga|DTCP anay|NNC ay|LM nagpakita|VBTS ng|CCB pasasalamat|RBS sa|CCT mga|DTCP langgam|NNC araw|NNC at|CCA gabiAng|PRC_CCP mga|DTCP langgam|NNC ay|LM may|VBH pananagutan|NNC din|RBI sa|CCT mga|DTCP itlog|NNC ng|CCB anay|NNC .|PMP Dinala|VBOF ng|CCB mga|DTCP langgam|NNC ang|DTC mga|DTCP itlog|NNC para|CCT sa|CCT mga|DTCP anay|NNC ,|PMC at|CCA itinago|VBTS ang|DTC mga|DTCP ito|PRO sa|CCT ilalim|JJD ng|CCB lupa|NNC .|PMP Nang|RBW mapisa|VBW ang|DTC mga|DTCP itlog|NNC ,|PMC pinangunahan|VBTS nila|PRP silang|PRP_CCP pakainin|VBOF ang|DTC mga|DTCP ugat|NNC ng|CCB makatas|VBW na|CCP halaman|NNC .|PMP Kaya|CCR naman|RBI ,|PMC ang|DTC mga|DTCP anay|NNC ay|LM nagpakita|VBTS ng|CCB pasasalamat|RBS sa|CCT mga|DTCP langgam|NNC araw|RBW at|CCA gabi|RBW .|PMP Isang|PRI_CCP araw|NNC ,|PMC habang|RBW dinadala|VBTR ng|CCB mga|DTCP langgam|NNC ang|DTC mga|DTCP itlog|NNC para|CCT ilagay|VBOF sa|CCT ilalim|JJD ng|CCB lupa|NNC ,|PMC nahulog|VBTS ang|DTC isa|PRI sa|CCT mga|DTCP itlog|NNC at|CCA gumulong|VBAF .|PMP Hindi|RBF napansin|VBTS ng|CCB mga|DTCP langgam|NNC ang|DTC nawawalang|VBTR_CCP itlog|NNC at|CCA nagpatuloy|VBTS sila|PRP .|PMP Ang|DTC itlog|NNC ay|LM napunta|VBTS sa|CCT isang|PRI_CCP maliit|JJD na|CCP dahon|NNC at|CCA napisa|VBTS pagkatapos|VBW ng|CCB ilang|PRQ_CCP araw|NNC .|PMP Nang|RBW ipanganak|VBOF ang|DTC anay|NNC na|CCP si|DTP Terry|NNP ,|PMC binuksan|VBOF niya|PRS ang|DTC kanyang|PRSP_CCP mga|DTCP mata|NNC at|CCA tumingin|VBAF sa|CCT paligid|NNC .|PMP Namangha|VBTS siya|PRS sa|CCT ganda|NNC ng|CCB kalikasan|NNC sa|CCT paligid|NNC niya|PRS .|PMP Uminom|VBAF siya|PRS mula|RBL sa|CCT mga|DTCP makatas|JJD na|CCP halaman|NNC hanggang|RBW sa|CCT mapawi|VBW niya|PRS ang|DTC kanyang|PRSP_CCP uhaw|NNC .|PMP Nagustuhan|VBTS niya|PRS ang|DTC lasa|NNC ng|CCB juice|FW at|CCA araw|NNC -|PMS araw|NNC itong|PRO_CCP iniinom|VBTR .|PMP Lumaki|VBAF at|CCA malusog|JJD si|DTP Terry|NNP .|PMP Isang|PRI_CCP araw|NNC may|VBH umatake|VBAF na|CCP lady|FW bug|FW !|PMS Nakita|VBTS siya|PRS ni|DTP Terry|NNP na|CCP paparating|VBTF ,|PMC kaya|CCR kinampay|VBOF niya|PRS ang|DTC kanyang|PRSP_CCP mga|DTCP pakpak|NNC at|CCA lumipad|VBAF palayo|RBD .|PMP Lumipad|VBAF siya|PRS hanggang|RBW sa|CCT bukid|NNC kung|RBK saan|RBQ nakatira|VBTS ang|DTC mga|DTCP anay|NNC kasama|CCB ng|CCB mga|DTCP langgam|NNC .|PMP "|PMSKamukha|JJD ko|PRS ang|DTC mga|DTCP insektong|NNC_CCP iyon|PRO !|PMQ  Lalapit|NNP ako|PRS at|CCA babati|NNC .|PMP
"|PMSHello|NNP !|PMS Magkamukha|VBW tayo|PRP ,|PMC "|PMS  sabi|VBS niya|PRS .|PMP
"|PMSBaka|CCU magkaugnay|VBW tayo|PRP !|PMS "|PMSNang|RBW marinig|VBW nila|PRP ang|DTC boses|NNC ni|DTP Terry|NNP at|CCA ang|DTC kanyang|PRSP_CCP mga|DTCP pakpak|NNC na|CCP pumapagaypay|VBTR_VBAF ,|PMC sila|PRP ay|LM namangha|VBTS .|PMP "|PMSSino|PRQ ka|PRS ?|PMQ Paano|PRQ ka|PRS nakakalipad|VBTR ?|PMQ "|PMSnagtanong|VBTS sila|PRP .|PMP  Nagulat|VBTS si|DTP Terry|NNP nang|RBW mapagtanto|VBW na|CCP hindi|RBF sila|PRP nakakakita|VBTR o|CCT lumilipad|VBTR_VBAF ,|PMC tulad|JJC ng|CCB magagawa|VBTF niya|PRS .|PMP
"|PMSHindi|RBF iyan|PRO totoo|RBT !|PMS "|PMSSila|PRP ay|LM umiyak|VBAF .|PMP "|PMSPinapakain|VBTR at|CCA pinoprotektahan|VBTR tayo|PRP ng|CCB mga|DTCP langgam|NNC .|PMP "|PMS  Pero|CCT tingnan|VBOF mo|PRS ako|PRS !|PMS
"|PMSpakiusap|NNC ni|DTP Terry|NNP .|PMP "|PMSBakit|PRQ sa|CCT tingin|NNC mo|PRS kaya|CCR kong|PRS_CCP lumipad|VBAF at|CCA makakita|VBW ?|PMQ  Dahil|CCR hindi|RBF ako|PRS lumaki|VBAF kasama|CCB ng|CCB mga|DTCP langgam|NNC .|PMP
"|PMSKahit|CCT na|CCP tama|JJD ka|PRS ,|PMC bakit|PRQ natin|PRP babaguhin|VBTF_VBOF ang|DTC mga|DTCP bagay|NNC kung|CCR ang|DTC mga|DTCP langgam|NNC ay|LM nagdadala|VBTR sa|CCT atin|PRSP ng|CCB pagkain|NNC at|CCA pinoprotektahan|VBTR tayo|PRP mula|RBL sa|CCT mga|DTCP kulisap|NNC ?|PMQ "|PMStapos|RBW tumingin|VBAF siya|PRS sa|CCT iba|PRI pang|RBI_CCP anay|NNC .|PMP  Tayo|NNP na!panahon|CDB na|CCP para|CCT ipakita|VBOF ang|DTC ating|PRSP_CCP pasasalamat|RBS sa|CCT mga|DTCP langgam|NNC .|PMP
"|PMSNakita|VBTS na|CCP ba|RBI ng|CCB sinuman|PRI sa|CCT inyo|PRSP ang|DTC mainit|JJD na|CCP sinag|NNC ng|CCB araw|NNC sa|CCT pamamagitan|NNC ng|CCB mga|DTCP dahon|NNC ng|CCB mga|DTCP puno|NNC ?|PMQ "|PMStanong|NNC niya|PRS .|PMP "|PMSNakita|VBTS na|CCP ba|RBI ng|CCB sinuman|PRI sa|CCT inyo|PRSP ang|DTC talon|NNC habang|RBW dumadaloy|VBTR_VBAF ito|PRO sa|CCT pagitan|NNC ng|CCB mga|DTCP bato|NNC sa|CCT ilog|NNC ?|PMQ O|NNPA ang|DTC kababalaghan|NNC ng|CCB dalawang|JJN_CCP magkayakap|VBW na|CCP ulap|NNC sa|CCT ilalim|JJD ng|CCB liwanag|NNC ng|CCB buwan|NNC ?|PMQ May|VBH buhay|NNC sa|CCT kabila|CCT ng|CCB parang|CCT .|PMP Kung|CCR mayroon|VBH kang|PRS_CCP mga|DTCP pakpak|NNC ,|PMC maaari|VBS kang|PRS_CCP lumipad|VBAF at|CCA magtago|VBAF mula|RBL sa|CCT mga|DTCP kulisap|NNC ,|PMC nang|RBW wala|VBN kailangan|VBS ng|CCB sinumang|PRI_CCP magpoprotekta|VBTF saiyo|NNC .|PMP "|PMSWalang|VBN_CCP may|VBH pakialam|NNC sa|CCT sinabi|VBTS ni|DTP Terry|NNP .|PMP  Tatlong|JJN_CCP anay|NNC lang|RBI ang|DTC nagpasya|VBTS na|CCP manatili|VBW sa|CCT kanya|PRSP .|PMP
"|PMS Kamukha|JJD mo|PRS kami|PRP !|PMS "|PMSNakuha|VBTS nilang|PRP_CCP kumbinsihin|VBOF ang|DTC dalawampung|JJN_CCP anay|NNC na|CCP umalis|VBAF sa|CCT bukid|NNC kasama|CCB ang|DTC mga|DTCP langgam|NNC .|PMP  Pinrotektahan|VBTR nila|PRP sila|PRP at|CCA sinabi|VBTS sa|CCT kanila|PRSP ang|DTC tungkol|RBR sa|CCT kagandahan|NNC ng|CCB lahat|PRI ng|CCB nakikita|VBTR nila|PRP .|PMP
"|PMSTingnan|VBOF mo|PRS !|PMS "|PMSsigaw|NNC ni|DTP Sonu|NNP .|PMP  Si|DTP Rina|NNP ay|LM nakakita|VBTS ng|CCB maliit|JJD na|CCP langgam|NNC patungo|RBL sa|CCT malaking|JJD_CCP daga|NNC .|PMP
"|PMSMiaaww|NNP "|PMS  sabi|VBS ng|CCB maliit|JJD na|CCP kuting|NNC at|CCA nagsimulang|RBD_CCP linisin|VBOF ang|DTC kanyang|PRSP_CCP mga|DTCP paa|NNC .|PMP
"|PMS Di|RBF ako|PRS matatakot|VBTF .|PMP Kaya|CCR ko|PRS '|PMS to|FW !|PMS "|PMSPagkatapos|VBW ,|PMC nakita|VBTS niya|PRS ang|DTC lawa|NNC .|PMP  Kumikislap|NNP ang|DTC mga|DTCP bituin|NNC sa|CCT tubig|NNC .|PMP
"|PMS Nobel|NNP Peace|NNP Prize|NNP "|PMS  .|PMP
"|PMSHuwag|RBF kang|PRS_CCP malikot|JJD .|PMP Hayaan|VBOF mong|PRS_CCP tingnan|VBOF ka|PRS ng|CCB duktor|NNC .|PMP Ayaw|RBF ito|PRO ni|DTP Veha|NNP pero|CCT hinayaan|VBTS nya|PRS lang|RBI ang|DTC ate|NNC .|PMP "|PMSAyos|NNP "|PMS ,|PMC ang|DTC sabi|VBS ni|DTP Vita|NNP ,|PMC "|PMS  Maganda|JJD ang|DTC temperatura|NNC ng|CCB iyong|PRSP_CCP katawan|NNC .|PMP

In [7]:
import pandas as pd


sentenceDF = set(sentenceList)
sentenceDF = pd.DataFrame(sentenceDF,columns=['sentence'])
sentenceDF['sentence_without_postag'] = sentenceDF['sentence'].apply(lambda x: [a.split('|')[0] for a in x.split(' ')])
sentenceDF['sentence_without_postag'] = sentenceDF['sentence_without_postag'].apply(lambda x: ' '.join(x))
sentenceDF

,sentence,sentence_without_postag
0,Kasama|CCB niyang|PRS_CCP namumuhay|VBTR nang|...,Kasama niyang namumuhay nang matiwasay ay ang ...
1,"""|PMS Wakas|NNP Magkakatabi|VBW sa|CCT kagubat...",""" Wakas Magkakatabi sa kagubatan ngunit hindi ..."
2,Dose|NNP -|PMS dosenang|NNC_CCP tren|NNC ang|D...,Dose - dosenang tren ang dumaraan sa paligid n...
3,Ang|DTC aking|PRSP_CCP mga|DTCP kaibigan|NNC !...,Ang aking mga kaibigan !
4,Saan|PRQ :|PMS sa|CCT likuran|NNC ng|CCB paara...,Saan : sa likuran ng paaralan .
...,...,...
9873,Pinatunog|VBTS ni|DTP Cici|NNP ang|DTC mga|DTC...,Pinatunog ni Cici ang mga bote .
9874,sabi|VBS niya|PRS sa|CCT kaniyang|PRSP_CCP sar...,sabi niya sa kaniyang sarili .
9875,Kaya|CCR naman|RBI ang|DTC mga|DTCP tao|NNC gu...,Kaya naman ang mga tao gustong - gustong sumak...
9876,Siya|PRS ay|LM humihip|VBAF at|CCA humihip|VBA...,Siya ay humihip at humihip at
9877,Nagpalipat|NNP -|PMS lipat|FW na|CCP siya|PRS ...,Nagpalipat - lipat na siya sa iba - ibang daho...

In [8]:
sentenceDF.loc[sentenceDF['sentence'].str.contains('"|PMS') & sentenceDF['sentence'].str.contains('sabi')]

,sentence,sentence_without_postag
5,"""|PMS magkakarugtong|JJD na|CCP sinabi|VBTS ng...",""" magkakarugtong na sinabi ng bantay . Biglang..."
45,"""|PMS Pogs|NNP ,|PMC akala|VBS ko|PRS talaga|R...",""" Pogs , akala ko talaga alimasag iyon , mabut..."
53,"""|PMS sabi|VBS ni|DTP '|PMS Tay|NNP Kanor|NNP ...",""" sabi ni ' Tay Kanor habang iniaabot ang daho..."
59,"""|PMS Sige|NNP ,|PMC ""|PMS sabi|VBS ni|DTP Ku...",""" Sige , "" sabi ni Kurakog ."
95,"""|PMS sabi|VBS ng|CCB higanteng|JJD_CCP maamo|...",""" sabi ng higanteng maamo ang mata . "" Ayokon..."
...,...,...
9780,"""|PMS sabi|VBS ni|DTP Basha|NNP .|PMP ""|PMS S...",""" sabi ni Basha . "" Susunod . ."
9781,"""|PMS pagtatapat|VBW ni|DTP Tessie|NNP .|PMP ""...",""" pagtatapat ni Tessie . "" Ang sabi niya , ' ..."
9803,"""|PMS Tanong|NNC ng|CCB Napakatangkad|NNP na|C...",""" Tanong ng Napakatangkad na Libraryan . Inaak..."
9827,"""|PMS nasabi|VBTS na|RBI lang|RBI siya|PRS sa|...",""" nasabi na lang siya sa kaniyang sarili . Hum..."
9847,"""|PMS Ibang|PRI_CCP klase|NNC na|CCP ang|DTC m...",""" Ibang klase na ang mga laro namin ni Nanay S..."

In [11]:
sentenceDF.iloc[5].values.tolist()

['"|PMS magkakarugtong|JJD na|CCP sinabi|VBTS ng|CCB bantay|NNC .|PMP Biglang|RBD_CCP tumugtog|VBAF ang|DTC tambol|NNC .|PMP "|PMS  Ako|PRS \'|PMS y|FW may|VBH sikretong|JJD_CCP sasabihin|VBTF .|PMP\n',
 '" magkakarugtong na sinabi ng bantay . Biglang tumugtog ang tambol . "  Ako \' y may sikretong sasabihin .']