In [17]:
# add more sentences from the file to the list
sentenceList = []
f = open('textAllFil_postagged_FINAL.txt', 'r')
lines = f.readlines()

gettingQuote = False
temp_sentence = ""

for line in lines:
    if line == '"|PMS':
        gettingQuote = not gettingQuote
    else:
        if gettingQuote:
            temp_sentence+=f'{line} '
        else:
            if len(temp_sentence) > 0:
                sentenceList.append(temp_sentence)
                temp_sentence = ""
            else:
                sentenceList.append(line)
f.close()

In [18]:
import pandas as pd


sentenceDF = set(sentenceList)
sentenceDF = pd.DataFrame(sentenceDF,columns=['sentence'])
sentenceDF['sentence_without_postag'] = sentenceDF['sentence'].apply(lambda x: [a.split('|')[0] for a in x.split(' ')])
sentenceDF['sentence_without_postag'] = sentenceDF['sentence_without_postag'].apply(lambda x: ' '.join(x))
sentenceDF

,sentence,sentence_without_postag
0,"Ngayon|RBW ,|PMC hindi|RBF na|RBI ako|PRS nahi...","Ngayon , hindi na ako nahihiya sa aking buhok ..."
1,"Pero|CCT ngayon|RBW ,|PMC ginamit|VBOF niya|PR...","Pero ngayon , ginamit niya ito nang dahan - da..."
2,sinabi|VBTS ng|CCB magsasaka|NNC na|CCP papata...,sinabi ng magsasaka na papatayin ka para sa ka...
3,Mabilis|RBD akong|PRS_CCP pumunta|VBAF sa|CCT ...,Mabilis akong pumunta sa paligid ng bahay .
4,Sila|PRP ba|RBI ay|LM patingkayad|RBD na|CCP u...,Sila ba ay patingkayad na umiikot sa bahay upa...
...,...,...
17839,Ama|NNC !|PMS\n,Ama !
17840,Nagtataka|VBTR siya|PRS kung|CCR makakahanap|V...,Nagtataka siya kung makakahanap ba siya ng anu...
17841,Inilibot|VBTS ng|CCB guro|NNC si|DTP Vanna|NNP...,Inilibot ng guro si Vanna at ang kanyang mga k...
17842,Nakita|VBTS ko|PRS si|DTP tatay|NNC na|CCP tum...,Nakita ko si tatay na tumutulong .
17843,Iba|PRI man|RBI sa|CCT ating|PRSP_CCP paningin...,"Iba man sa ating paningin , bigay pa rin sila ..."

In [23]:
sentenceDF.loc[sentenceDF['sentence'].str.contains('"|PMS') & sentenceDF['sentence'].str.contains('sabi')]

,sentence,sentence_without_postag
95,Inutusan|VBTS ng|CCB kawal|NNC si|DTP Kayumang...,Inutusan ng kawal si Kayumangging Kuneho na sa...
1511,sabi|VBS ni|DTP Tatay|NNP Aldo|NNP na|CCP naka...,sabi ni Tatay Aldo na naka - uniporme pang pan...
1547,May|VBH sasabihin|VBTF akong|PRS_CCP sikreto|N...,"May sasabihin akong sikreto , Rohan !"
1746,"Tumalon|NNP ,|PMC umindak|VBAF ,|PMC sabay|RBD...","Tumalon , umindak , sabay - sabay sabihing baa..."
2031,sabi|VBS ng|CCB batang|JJD_CCP kambing.nagsimu...,sabi ng batang kambing.nagsimula gumuhit ng pa...
...,...,...
17145,sabi|VBS ng|CCB isang|PRI_CCP panakot|NNC saba...,sabi ng isang panakot sabay buntong - hininga .
17254,Pagkatapos|VBW na|CCP sabihin|VBOF '|PMS yon|P...,Pagkatapos na sabihin ' yon ni Nanoy ay tumali...
17466,sabi|VBS ni|DTP Kokoy|NNP sa|CCT umang|NNC_CCP...,sabi ni Kokoy sa umang - umang .
17766,"At|CCA pag|CCR -|PMS uwi|NNCA mo|PRS ,|PMC dap...","At pag - uwi mo , dapat mong sabihin sa iyong ..."
17813,Pum|NNP Anh|NNP conducts|FW writers|FW '|PMS w...,Pum Anh conducts writers ' workshops with chil...

In [27]:
sentenceDF.iloc[2031].values.tolist()

['sabi|VBS ng|CCB batang|JJD_CCP kambing.nagsimula|NNC gumuhit|VBAF ng|CCB paru|FW -|PMS paro|NNC ,|PMC bangka|NNC at|CCA puno|NNC ang|DTC maliit|JJD na|CCP kambing|NNC habang|RBW kumukuha|VBTR_VBAF ng|CCB mga|DTCP dahon|NNC at|CCA bulaklak|NNC ang|DTC biik|NNC upang|CCB idagdag|VBOF sa|CCT ginuhit|VBOF na|CCP larawan|NNC .|PMP\n',
 'sabi ng batang kambing.nagsimula gumuhit ng paru - paro , bangka at puno ang maliit na kambing habang kumukuha ng mga dahon at bulaklak ang biik upang idagdag sa ginuhit na larawan .']